### ISSUE TITLE
Can't make a world type conquest

### ISSUE THREAD

**Issue by Potsukin** [Conquest-Reforged/ConquestReforged#1]
When tried to make a world type " Conquest", cannot choose customize. And when make a new world "loading world" takes forever. Probably something happening with other mods.

**Comment by HIPPOKLEIDES** [comment]
Customization options haven't been implemented yet, so the customization button is just there for future additions. Creating a new conquest world may take longer than vanilla world due as a result of generating a more complex landscape. Are you at least able to enter the world eventually?

**Comment by Potsukin** [comment]
No, after 10 minutes  of "loading world" I was force quit Minecraft.

**Comment by HIPPOKLEIDES** [comment]
Can you share your latest log?

**Comment by Potsukin** [comment]
Latest.log? here: https://pastebin.com/XxKZMhQw

**Comment by wunder-bread** [comment]
Try to just run ConquestReforged 1.12.2 without all the other crazy mods you have. And it looks like you need to update your video drivers.

**Comment by Potsukin** [comment]
Run ConquestReforged 1.12.2 only doesn't make sense.

**Comment by HIPPOKLEIDES** [comment]
The error is being caused by the Recurrent Complex Mod, which creates an error when Conquest tries to generate a structure such as the Ocean Monument, as shown here:

java.lang.ClassCastException: ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler$1 cannot be cast to com.conquestreforged.common.world.ModStructureOceanMonument

**Comment by Potsukin** [comment]
Structure generation of Reccurrent Complex was disabled by config and works no problem with any other world generate mod. Remenber that latest.log is not a crash log, I was shutting down Minecraft by myself.

**Comment by Potsukin** [comment]
Structure generation of Reccurrent Complex was disabled by config and works no problem with any other world generate mod or structure generation mod. Normally RC's structure generation configuration does not affect to other mods .

**Comment by dags-** [comment]
It's CR doing the casting to be fair.

To ensure compatibility we should really be using minecraft's interfaces/parent types as much as possible in fields, local variables etc.

In this case (`ModGeneratorOverworld`), could the field `oceanMonumentGenerator ` not be of the type:
```
net.minecraft.world.gen.structure.MapGenStructure
```

And not:
```
com.conquestreforged.common.world.ModStructureOceanMonument
```

**Comment by TheProtoss-YT** [comment]
A comment from the peanut gallery - I had the same issue with Recurrent Complex, I don't believe in overdoing it with additional mods, and when I do I hide my crash reports from WunderBread ... LOL.  Conquest Reforged and Recurrent Complex are very dear to me (and my future plans for world domination ... haha) - just my two cents, have a good day all!
