### ISSUE TITLE
Mining diorite causes it to disappear

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#100]
Using a flint pickaxe from Tinkers Construct on Diorite causes it to disappear when mined, whereas a flint pickaxe from conquest does not.

**Comment by dags-** [comment]
Guessing Tinkers Construct's tools don't extend minecraft's `ItemTool` class.

Will try come up with a fallback generic way of determining which items are tools and what class of tool they are. May otherwise have to wait until 1.13.

**Comment by KnightMiner** [comment]
What do you need the material class for? If it is just harvest level, call `getHarvestLevel`, it works with any item.

**Comment by dags-** [comment]
CR uses a json-backed system for configuring drops, looking up firstly the tool type (axe, pickaxe etc) and then the tool material (wood, stone etc) against a given blockstate.

Currently uses `ItemTool.getToolMaterial`, but we could probably work backwards from a harvest level to guess the material as a fallback for non-ItemTool-extending tools.

**Comment by mitchngwen** [comment]
So what is the fix?

**Comment by CreativeRealms** [comment]
There’s won’t be a fix for 1.12.2 as it’s not getting any more updates. It might get looked into for 1.14.4 though.

**Comment by dags-** [comment]
Shouldn't need anything special doing in 1.14 since we don't need to pack different material variants onto blockstates of a single block
