### ISSUE TITLE
World Generation bug (1.12)

### ISSUE THREAD

**Issue by nanaspam08N** [Conquest-Reforged/ConquestReforged#101]
![2018-04-28_20 42 22](https://user-images.githubusercontent.com/38817694/39399832-4cdf06f0-4b25-11e8-9325-63777fafb1d6.png)

**Comment by SirChamomile** [comment]
Woah! That's awesome. I would totally play in that world :D

**Comment by HIPPOKLEIDES** [comment]
Haven't seen this after generating hundreds of worlds using CR generation, so this has to be something on your end.
