### ISSUE TITLE
[Suggestion] Low frequency of Dirt and Stone

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#102]
It's difficult to find enough resources to craft basic items and do any sort of landscaping early in the game. It's fine that it's difficult, but it ends up taking a long time getting started. While I don't mind strip-mining large swaths of land for regular dirt and stone blocks, it would be great if there were small patches of vanilla dirt and stone generated below ground near the surface to alleviate some of this problem. Specifically in the many biomes that have no stone below the surface layer as their primary blocks are things like Diorite and Granite. This can be done with another mod such as CoFH Core, but I'd prefer to keep the amount of world generation mods down.

**Comment by HIPPOKLEIDES** [comment]
Why does one need more stone and dirt? I'm not aware of anything that can be crafted with dirt, and I think the essential recipes for stone should work for Conquest natural stones, diorite, granite, etc (though I admit I should add these to oredictionary)

**Comment by SirChamomile** [comment]
I'm thinking mainly for terraforming, or building grassy areas underground or in places without grass. This also is important for things like larger scale farming. It just seems a shame to have such beautiful world gen and then have to strip the first couple layers off a large swath of land. I could accomplish this with another mod like Botania, but it's not a great solution because I feel as though Conquest needs to stand on its own.

Maybe the best way to solve this would be to allow the user to craft dirt-like blocks into dirt, that way we wouldn't have to go picking carefully over a terrain to pick out the dirt blocks. What would be especially great if you could add recipes for certain underground rock that is unsuitable for building and unusable for craft such as cliffstone. If you added a recipe where you could use the hammer to turn cliff stone into cobblestone that would be fantastic. The cobble textures in conquest are fantastic, and it's a shame we don't always have the option to use them.

That all being said it's not my mod and these are just suggestions. I'll totally understand if you just stick to the roadmap.

**Comment by HIPPOKLEIDES** [comment]
For dirt, maybe something like this? We have plans to add different types of farmland for various dirt blocks. https://cdn.discordapp.com/attachments/435440808502493204/435826163710165032/2018-04-11_20.12.50.png

Also, for stone, I know Monsterfish will work on cobblestones for various types of stone eventually.

**Comment by SirChamomile** [comment]
This is a beautiful slice of sedimentary layers! 

I'm not sure how your algorithm works, but I had two additional options in mind. The first is to add something like you've done here, but disperse them a little more so it's not a constant layer? That way it doesn't disrupt your beautiful distribution. Something tells me that could be a complex process, and a little difficult to code. The second option that came into my mind was to do a thicker layer of dirt, maybe 4-5 thick under marshy or boggy terrain. This could easily represent the thick layers of peat and and detritus - many layers of organic sediment - that you get in these formations. Your marshes, swamp and bog areas usually spawn flat, and those flat features would make mining under them easy. That way, if you needed a lot of dirt for a build, there would be surefire options, and not super rare ones for important building materials.

It's great to hear about the farmland and the cobble. I really look forward to that and I'm less concerned know knowing a little bit more about that part of the roadmap.

**Comment by lungora** [comment]
Definitely support this. Pockets of Dirt, Gravel, Vanilla Stone would all be wonderful especially the dirt which has honestly ended up kinda hard to obtain with all the new soil blocks. In addition I would like to ask for a return of underground lakes/aquifiers because I have noticed none exist while doing extensive dcaving today and it seems like a missed feature.

**Comment by SirChamomile** [comment]
@lungora 

You just have to look in the right places ;)

![2018-05-01_00 23 55](https://user-images.githubusercontent.com/23204608/39503746-2de4179e-4d8d-11e8-974c-aa1e59aecedc.png)

**Comment by CreativeRealms** [comment]
World gen will be reworked in 1.14.
