### ISSUE TITLE
ConquestReforged VS Bibliocraft -- 1.12.2

### ISSUE THREAD

**Issue by ano19920** [Conquest-Reforged/ConquestReforged#103]
itʻs happened twice now. on a creative flatworld, i press E to get to inventory so that i can go check out all the new stuff. however, it *immediately* crashes my game. something is causing issues with the wood textures somewhere...

[crash-2018-04-28_14.20.17-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/1958111/crash-2018-04-28_14.20.17-client.txt)

[crash-2018-04-28_14.24.30-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/1958112/crash-2018-04-28_14.24.30-client.txt)

**Comment by HIPPOKLEIDES** [comment]
This is an issue with the Bibliocraft mod, which hasn't fully or properly implemented their custom model class (and therefore it conflicts with our block selection GUI)

**Comment by ano19920** [comment]
Ah, i see! well, i removed the bibliocraft mod about an hour ago. conquest reforged > bibliocraft! thanks for checking out my crash report. :)
