### ISSUE TITLE
Crash when opening inventory with other mods installed

### ISSUE THREAD

**Issue by taluseve** [Conquest-Reforged/ConquestReforged#106]
[crash-2018-04-28_16.55.14-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/1958172/crash-2018-04-28_16.55.14-client.txt)

**Comment by HIPPOKLEIDES** [comment]
This is an issue with the Bibliocraft mod, which hasn't fully or properly implemented their custom model class (and therefore it conflicts with our block selection GUI)
