### ISSUE TITLE
Incompatible with Tinkers Construct Tools: Hammer/Pickaxe -> Breaking blocks with Tinkers Construct doesnt drop stone/cobblestone

### ISSUE THREAD

**Issue by Paepodlun** [Conquest-Reforged/ConquestReforged#107]
Tinkers Construct Tool Hammer and Pickaxe aren't dropping by breaking stoneblocks "cobblestone" or "stone" (no block loot") - Ores are dropping 
and the 
other tools like shovel or axe are working from Tinkers Construct (dropping wood and sand...)

**Comment by Paepodlun** [comment]
# Tested some things wich blocks stone do work: All instead of:
## ONLY NOT WORKING: minecraft:stone; // (stone variants ->) minecraft:dolomite; minecraft:granite; minecraft:diorite

**Comment by Paepodlun** [comment]
No. They'll fix it probably with the next update.

Am Sa., 3. Nov. 2018 um 04:22 Uhr schrieb ClaudiusMinimus <
notifications@github.com>:

**Comment by ClaudiusMinimus** [comment]
Thank you. I found this on the TC issue tracker. Don't if it will be of use: 
https://github.com/SlimeKnights/TinkersConstruct/issues/3516

**Comment by ClaudiusMinimus** [comment]
Packed Ice is also affected by this issue. Not only do Tinkers Construct picks destroy Packed Ice, but Tiny Progressions picks as well.

**Comment by Paepodlun** [comment]
It's annoying :D Hope there will be an update for 1.12.2 soon. Some
crafting recipes arent working too atm.

Am Mo., 5. Nov. 2018 um 23:02 Uhr schrieb ClaudiusMinimus <
notifications@github.com>:

**Comment by lukin7788** [comment]
hi, 
are there any news to this issue? Stone still drops no Cobblestone wenn harvest with a TC Pickaxe!

**Comment by lukin7788** [comment]
So I guess there ist no further CR Uptade for 1.12.? The Bugs with TC are still there and I hope they will fix it in 1.13/14 Versions?

**Comment by Paepodlun** [comment]
As far as i know, CR won't get a bugfix on 1.12 and they are on 1.13/14
atm. But I don't know if they fix this bug.

Am Sa., 20. Juli 2019 um 16:31 Uhr schrieb lukin7788 <
notifications@github.com>:
