### ISSUE TITLE
MaxPermSize

### ISSUE THREAD

**Issue by SirXudes** [Conquest-Reforged/ConquestReforged#108]
When I try and open 1.12.2 it says: Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0

The game doesnt open and I get back to the launch menu

**Comment by HIPPOKLEIDES** [comment]
This isn't a bug, but rather something that has gone wrong in your installation. For help be sure to go to our Support channel on discord (can't help you right now anyway as what you typed isn't something that would cause a crash)

**Comment by Frouxrious** [comment]
I have the same issue: 

Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Conquest Reforged.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D1
	OptiFine Build: 20180323-135452
	Render Distance Chunks: 16
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.13492 Compatibility Profile Context 22.19.677.257
	OpenGlRenderer: Radeon(TM) RX 460 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
[19:53:47] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Corentin Hérault\Desktop\.\instances\ConquestReforgedBasic1.12.2\minecraft\crash-reports\crash-2019-08-25_19.53.46-client.txt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Process ended with code: -1
