### ISSUE TITLE
custom trees

### ISSUE THREAD

**Issue by Kurgahn** [Conquest-Reforged/ConquestReforged#11]
[The new trees look really nice but I have found a few issues. I couldn't find any jungle wood and darkoak wood within the new trees at all which might be a problem if you want to use those wood types for building. An other thing is that leaves rarely match the wood which might be confusing if you want to grow a tree (bamboo uses birch leaves for example) and I think too many trees use acacia wood. I'm also not a fan of mixed leaves since it doesn't make sense, could be confusing and doesn't look nice (though that might be personal preference). I know that more wood and leaf types have not been necessary for creative but I think generated survival worlds should make more sense. 
Lastly there is at least one tree model with a bee hive which is a manmade block and would not appear in nature.

**Comment by Kalagath** [comment]
I'd like to give some input on the trees as well.
Mainly I think it's problematic that they have a very inconsistent style so far. Some use only full blocks or full blocks spiced up with fences and walls. Others make use of all the Reforged blocks (like vertical slabs, stairs, trapdoors). 
So it makes the whole world generation aestethics seem inconsistent.
Another inconsistency is tree height. Some biomes have proper big trees (Lorien forest, Jungle) while others have very small trees, especially the birch forest. (Actual birch trees grow pretty tall)
Personally I think they should not be beneath a certain height. Tall trees add to the immersion and realism of the world.
Also if I might ask, who is making the trees? It seems like there are different people involved and that adds to the inconsistent look. (Just put Loudim up for the task :P)
As for the unavilable wood types Kurgahn mentioned, I'm sure you are aware and will add them soon enough

**Comment by Kalagath** [comment]
Btw @Kurgahn that beehive you mention is actually a hornets nest and they do make these kind of nests naturally. As do wasps.

**Comment by Kurgahn** [comment]
there are trees with the hornets nest but there are also trees with the bee hive (made of rope)

**Comment by Kalagath** [comment]
Oh I see, didn't find those yet. I agree in that case ;)

**Comment by lungora** [comment]
Definitely gonna second the ask for less Acacia wood. It's too much everywhere and by far the most ugly plank type. Swap some log types for the next update please.

**Comment by CreativeRealms** [comment]
Trees are going to be reworked for 1.14.
