### ISSUE TITLE
Andesite Recipes

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#110]
Andesite and Natural Andesite found in world gen can't be crafted into Smooth or Polished Andesite. Smooth Andesite is crafted using Dolomite, and Polished Andesite is crafted with Granite...

**Comment by HIPPOKLEIDES** [comment]
names are completely changing and being reworked in 1.13, so by then this won't really be relevant (won't work on it in 1.12 due to the flattening coming and lang file format changing as well)

**Comment by SirChamomile** [comment]
I'll just do it with CraftTweaker then. Thanks.
