### ISSUE TITLE
Crash on startup on macOS (Sierra, 10.12.6)

### ISSUE THREAD

**Issue by VektorPixel** [Conquest-Reforged/ConquestReforged#112]
Hello,

i installed/updated conquest-reforged via the launcher 4.3.7 but on startup the game crashes with the following error:
java.lang.NoClassDefFoundError: com/mojang/text2speech/NarratorOSX

[crash-2018-04-28_23.49.56-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/1958200/crash-2018-04-28_23.49.56-client.txt)

I also installed vanilla Minecraft (1.12.2) and it's running fine.

**Comment by dags-** [comment]
I'm wondering if 1.12 has some new mac os specific libraries that obviously wouldn't be included in the modpack phil made since he's on windows

**Comment by VektorPixel** [comment]
I found out that in vanilla 1.12.2 there is a .jar file named 
`"java-objc-bridge-1.0.0-natives-osx.jar"` at the 
`"<Application Support>/minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/"` path.
This file exists also at the very similar path 
`"<Application Support>/minecraft_Conquest/libraries/ca/weblite/java-objc-bridge/1.0.0"` in conquest.
Both files have the same sha checksum: 08befab4894d55875f33c3d300f4f71e6e828f64.

But at the vanilla side there is also the file `"java-objc-bridge-1.0.0.jar"`
which doesn't exists in conquest.

Copying this file to the folder in conquest doesn't change anything.
Maybe it needs to be added to the project or something.

**Comment by HIPPOKLEIDES** [comment]
Should be fixed for OSX users now. Be sure to completely reinstall the modpack

**Comment by VektorPixel** [comment]
It works fine now.
Thank you!

**Comment by arkaik8** [comment]
Thank You for all you hard work on  fixing the OS X issue so quickly.

The launcher works perfectly now on my Mac
