### ISSUE TITLE
Crash when opening inventory in creative, incompatability with mekanism

### ISSUE THREAD

**Issue by Mongole** [Conquest-Reforged/ConquestReforged#113]
[Crash Report.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/1958270/Crash.Report.txt)
The crash only occurs when playing in creative mode and not survival, happens as soon as you try to open the inventory

**Comment by dags-** [comment]
I'm looking into how best to handle it. seems a lot of mods do some funky stuff I haven't accounted for :/

**Comment by HIPPOKLEIDES** [comment]
Seems to be fixed on normal blocks in Mekanism, but broken for blocks with nbt or damage values
