### ISSUE TITLE
Gold coins

### ISSUE THREAD

**Issue by steelropes** [Conquest-Reforged/ConquestReforged#114]
make 8-9 gold coins craftable into a gold nugget.
and gold nugget gives you 8-9 coins.

8 because 64 is divisble by 8, 9 to fit the theme of 9.

**Comment by MedievalPigeon213** [comment]
gold coins are already a feature. Just rename a gold nugget to "A gold coin" or rename a iron nugget to "A silver coin"

**Comment by MedievalPigeon213** [comment]
you can get them. Just rename a gold nugget to "A gold coin" and there. You will need the vanilla Conquest Resource pack though

**Comment by CreativeRealms** [comment]
Coins won't be craft able since they are designed to be part of server economy systems and/or will replace emeralds in villager trades.
