### ISSUE TITLE
Connected Textures not working

### ISSUE THREAD

**Issue by MedievalPigeon213** [Conquest-Reforged/ConquestReforged#119]
The dirt block in the image doesn't have connected textures anymore. Is it because I combined the Conquest Resource pack with the Conquest Reforged Resource pack?

https://imgur.com/a/TgOT5q2 Straw bale just for reference to show that it does work but not with the dirt block anymore :(

**Comment by HIPPOKLEIDES** [comment]
Those overlay connections have not been implemented into Conquest Reforged yet.
