### ISSUE TITLE
Converted world spawn glitches 

### ISSUE THREAD

**Issue by iwoftv** [Conquest-Reforged/ConquestReforged#120]
![2018-04-29_07 48 08](https://user-images.githubusercontent.com/38829289/39403850-1110e0a6-4b86-11e8-994b-1c0051387c6d.png)
![2018-04-29_07 47 44](https://user-images.githubusercontent.com/38829289/39403852-147f2d56-4b86-11e8-9918-997351fdc4fa.png)
the glass doesnt connect to some CR blocks, opened shutters spawn diffrently, ladders are at diffrent positions

**Comment by HIPPOKLEIDES** [comment]
Added conversions for these to the converter. Latest version should do the trick for the shutters and ladders now. Glass is also fixed
