### ISSUE TITLE
Campfire doesnt cast light

### ISSUE THREAD

**Issue by iwoftv** [Conquest-Reforged/ConquestReforged#126]
![2018-04-29_11 54 59](https://user-images.githubusercontent.com/38829289/39405353-22482d7a-4ba4-11e8-9576-e4ce04cc42af.png)
Campfire doesnt cast light

**Comment by CreativeRealms** [comment]
Right click the block and it should toggle light emission.

**Comment by HIPPOKLEIDES** [comment]
^ also removed fire on the campfire that doesn't emit light
