### ISSUE TITLE
Rustic Bed not sleeping properly.

### ISSUE THREAD

**Issue by lungora** [Conquest-Reforged/ConquestReforged#132]
Rustic bed wouldnt let me properly sleep
it triggered the achievement, and teleported me ontop of the bed, but didnt do the regule sleep lay down nor pass the night

Creating and using a White Bed instead was all fine, Rustic Bed was still broken after.

**Comment by HIPPOKLEIDES** [comment]
fixed functionality of modded beds. thanks for the report
