### ISSUE TITLE
New recipe for ingots, nuggets, blocks.

### ISSUE THREAD

**Issue by steelropes** [Conquest-Reforged/ConquestReforged#137]
Currently the recipes for ingots, nuggets, and blocks, are based on the number 9. Make all recipes like this based on the number 8 instead, because 64 is divisible by 8. This will allow for easy item stacking in an economy. Example: 1 gold block = 8 ingots = 64 nugget = 512 coins

1 gold coin = 8 silver coins = 64 bronze coins.

1 stack of bronze coins = 1 gold coin.
1 stack of silver coins = 8 gold coins.
8 gold coins = 1 platinum coin etc.

Making everything based on the number 8 rather than 9 is simply better, because the max stack is 64, and 8 is the highest integer that fits into 64 that you can fit in the crafting table.

**Comment by CreativeRealms** [comment]
Recipes will all be changed in 1.14.
