### ISSUE TITLE
[Models] Some arch models do not form correctly

### ISSUE THREAD

**Issue by spinach80186** [Conquest-Reforged/ConquestReforged#138]
Example: Dark Roman Brick Corner Arch facing outward appears as a corner stair instead of the corner arch model, which does exist.

I converted an old world to 1.12.2 with the conversion tool and when I loaded it, there were corner arches in the buildings, but when I tried to place a new one by hand it rendered a stair.

**Comment by HIPPOKLEIDES** [comment]
probably will save it for 1.13 since blockstates were be completely redone in that update.
