### ISSUE TITLE
[Textures] Engraved V Uses Marble, but Every Other Letter Has Smooth Marble

### ISSUE THREAD

**Issue by spinach80186** [Conquest-Reforged/ConquestReforged#139]
![reforged-texture-issue](https://user-images.githubusercontent.com/38845127/39412592-eb064934-4bec-11e8-8b05-86e1d6add22e.png)

The engraved letter block uses smooth white marble, except for the V, which uses regular marble. You might miss it at first, but it is a yellower shade and a bit more gritty.

**Comment by HIPPOKLEIDES** [comment]
fixed, thanks
