### ISSUE TITLE
Issue: Stone Tools

### ISSUE THREAD

**Issue by Ashurthebear** [Conquest-Reforged/ConquestReforged#14]
In 2/18 patch. "-stone tools can be made out of naturally generated stone ". 

I see no recipes for stone tools at all. I tried several types of stone in a traditional pick axe recipe (3 rock over 2 sticks).

I see two recipes for flint tools in the shown recipes, both the traditional wood one and one using actual flint in place of stone. Has flint tools replaced stone tools altogether? They appear to have the same name and durability, but different construction methods.

**Comment by HIPPOKLEIDES** [comment]
I skipped the vanilla stones, forgetting they couldn't be used for stone tools (they're in now, thanks for bringing this to my attention). The naturally generated mod stones should work for stone tools. For now I don't plan on adding all the stone recipes to the unlocking achievement as that'd just fill up the recipe book with a plethora of stone tool recipes.

Flint tools only replace wood tools, and their recipes are in the unlocking achievement as there are only 5 and they're a new idea for people.

**Comment by Ashurthebear** [comment]
I don't see recipe for a stone pick axe at all.
