### ISSUE TITLE
No recipe for the Smooth White Marble block (other than its own slabs)

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#140]
Smooth White Marble (the basis for all marble columns and stuff) cannot be crafted other than combining its own sub parts. 

So far (been a few weeks i played the 1.12.2 version), i've not encountered other naturally generated marble blocks besides "Rough Marble" and "Marble". So i conclude there might be a missing recipe that would allow to "smoothen" the natural Marble blocks.

(p.s. i gave myself all recipes to be sure i didnt miss anything)

![2018-04-29_21 00 52](https://user-images.githubusercontent.com/18398566/39412926-1f7b154c-4bf1-11e8-8372-b626753a6c59.png)
![2018-04-29_21 00 55](https://user-images.githubusercontent.com/18398566/39412927-1fbea0f0-4bf1-11e8-92a4-7315fab1473b.png)

**Comment by SebbePwnYou** [comment]
you will get the recipes when doing it in a crafting table as some require 3x3 instead of 2x2

**Comment by HIPPOKLEIDES** [comment]
^
