### ISSUE TITLE
marble bas corner block doesn't place normally

### ISSUE THREAD

**Issue by GerPac** [Conquest-Reforged/ConquestReforged#141]
The marble bas corner block doesn't place down in the same direction like all the other corner blocks do.

**Comment by dags-** [comment]
Please could you add a screenshot of the block with your `F3` debug screen open? 
It'll tell us exactly which block is affected on the right-hand side

**Comment by HIPPOKLEIDES** [comment]
rotations and collision boxes were a bit off. got them fixed now though
