### ISSUE TITLE
Incompatabilities with the following mods causes crash on launch 

### ISSUE THREAD

**Issue by dave1505** [Conquest-Reforged/ConquestReforged#143]
Hi! I made many experiences with different combinations of mods and noticed the game will crash if the following mods are loaded along ConquestReforged:

Biomes o' Plenty
Binnies Mods
Galacticraft core/Micdoodlecore/Galacticraft-Planets
IndustrialCraft 2
OpenBlocks/OpenModsLib
ImmersiveEngineeringcore/ImmersiveEngineering
Extrautils2
thutcore/thuttech

Thanks for the attention and Congratulations! for what you've done so far!

**Comment by dags-** [comment]
Please provide the crash-reports and log files

**Comment by dave1505** [comment]
`https://drive.google.com/open?id=11GZcrU7gEI0avLQCCYN_b9ke9WORxpQ1` here is the crash report

**Comment by dags-** [comment]
Minecraft 1.12 and below has a limit of 4096 blocks. Your crash report is saying that, combined, the mods you're using are trying to add more than that limit (CR adds a few thousand just by itself!).

Unfortunately you're going to have to choose some mods to play without.

On a positive note, 1.13 will remove this limit entirely :]

**Comment by dave1505** [comment]
thanks a lot for the help! I was getting really confused with this one!
