### ISSUE TITLE
Weird Deserts

### ISSUE THREAD

**Issue by MedievalPigeon213** [Conquest-Reforged/ConquestReforged#144]
Am I the only one who thinks the CR desert is a little spammy with rocks? Because if you look at the Sahara Desert for example it's a sea of sand. Maybe the desert could be split into two biomes. One based on north American deserts like death valley and the other based on the Sahara

**Comment by SirChamomile** [comment]
While I agree with this, I don't think the full breadth of this biome has been explored. I think it's very likely that in the future deserts will have subbiomes like deserthills which could feature rolling sand dunes as in RTG, and of course then there would be less scrub and dirt.

I do feel that perhaps there is just a tad bit too much non vanilla blocks mixed in to the surface.

**Comment by MedievalPigeon213** [comment]
The reason I am suggesting this if your wondering is to fix a bug with the Ice and Fire mod. 

Their deathworm mob can swim though sand blocks but with CR and the non sand blocks in the desert the deathworm gets stuck and often stays above the sand and ruins the scariness and the surprise

**Comment by SirChamomile** [comment]
Does fire and ice use the ore dictionary? That would make this problem go away pretty quick, except for the surface sandstone. But I guess that could be what you're talking about.

**Comment by MedievalPigeon213** [comment]
I will check

**Comment by MedievalPigeon213** [comment]
I sent a pm on discord to AlexThe666(Ice and Fire's dev)

**Comment by CreativeRealms** [comment]
Biomes are being completely redone in 1.15.2.
