### ISSUE TITLE
Bring back the Old 'Wall of Spruce logs' and 'Wall of Oak logs'

### ISSUE THREAD

**Issue by VucMC** [Conquest-Reforged/ConquestReforged#145]
The new textures of this block are not really usable in builds anymore and there's no replacement blocks currently that can replace them.
Which sucks because these blocks were heavily used.

Bringing the old textures back as a new block or changing the new ones back would be GREATLY APPRECIATED!

**Comment by Monsterfisch** [comment]
the old texture will not make a comeback but the current one will be adjusted accordingly to be a good middleground
