### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MedievalPigeon213** [Conquest-Reforged/ConquestReforged#146]
The game crashed whilst updating screen events
The game crashed whilst updating screen events
Error: java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapelessRecipes@3c1de227 Name: conquest:light_dirt_path_1_verticalslab_to_slab

**Comment by HIPPOKLEIDES** [comment]
Have you tried removing Foamfix? Are you on a server? If so, which one?

**Comment by MedievalPigeon213** [comment]
I was on Darwin Reforged.
I will uninstall JEI though

**Comment by HIPPOKLEIDES** [comment]
Seems like Darwin has fixed the issue on their end
