### ISSUE TITLE
Reinforced Wooden Gate (ID 1496) Has The Wrong Texture

### ISSUE THREAD

**Issue by spinach80186** [Conquest-Reforged/ConquestReforged#148]
![broken door](https://user-images.githubusercontent.com/38845127/39445400-eb725394-4c88-11e8-8f94-f0d2b93685ba.png)

As you can see in the picture, the door's top sections seem to be using the texture assigned to a broken door, but the door was just placed. IDs of the door blocks are as follows:

![door ids](https://user-images.githubusercontent.com/38845127/39445967-d3de3e58-4c8a-11e8-86ca-8508ce832927.png)

Where 1496:8 is the broken door piece. (top right)

**Comment by HIPPOKLEIDES** [comment]
This issue can occur when adding/removing various mods that add block to the game and/or entering an old world, leading to ids that are different in the world than during startup (which optifine uses). You can try hitting f3+t to reload optifine, but even this sometimes does not fully solve the issue.
