### ISSUE TITLE
Nice craftable stone items require vanilla stone, which barely exists.

### ISSUE THREAD

**Issue by lungora** [Conquest-Reforged/ConquestReforged#149]
Can we allow the crafting recipe for all the craftable types of stone like Hewn, and Stone Brick, and the white one, etc be able to be made with granite and perhaps gniess and well?

**Comment by HIPPOKLEIDES** [comment]
I don't think so. We have plans to add more stone brick and cobblestone variants in the future.

**Comment by SirChamomile** [comment]
@lungora This is really easy to do with CraftTweaker especially with the new CraftTweaker GUI. Just use the `/ctgui craftingtable` command with it installed, and it will give you a window where you can put the materials and the results (it just ghosts them). Select the shapeless box above the hotbar at the bottom, and then hit add. You should be all good to go. If you need more help just ping me on the discord.
