### ISSUE TITLE
Sitting on a mule strange design

### ISSUE THREAD

**Issue by iwoftv** [Conquest-Reforged/ConquestReforged#150]
![2018-04-30_21 57 20](https://user-images.githubusercontent.com/38829289/39447343-b987e9fa-4cc1-11e8-9df3-315a2ea52e2e.png)
![2018-04-30_21 57 41](https://user-images.githubusercontent.com/38829289/39447349-be052ef2-4cc1-11e8-8462-1aa96f30cd73.png)
While only sitting nothing happens but opening horse's inventory does this strange bug.

**Comment by HIPPOKLEIDES** [comment]
I'd recommend reporting this to whoever makes the shader-pack you're using at https://discord.gg/ABz5KgQ or the pack's forum post, as we don't touch mule inventories.
