### ISSUE TITLE
Vanilla fences connect to railings

### ISSUE THREAD

**Issue by talset333** [Conquest-Reforged/ConquestReforged#154]
Vanilla fences connect to all the railing blocks

**Comment by talset333** [comment]
They also connect to weapon racks

**Comment by talset333** [comment]
Trapdoors / ladders as well. So probably all mod blocks

**Comment by HIPPOKLEIDES** [comment]
fixed for these. also made it so stuff like torches can be placed on and fences/panes can connect to the appropriate side of trapdoors
