### ISSUE TITLE
Leggings Need Rebalancing

### ISSUE THREAD

**Issue by ItsCestial** [Conquest-Reforged/ConquestReforged#156]
Bronze and steel leggings have more armor than they should in comparison to the base game armors. Steel leggings end up being better than diamond leggings because the trade-off of 1 less armor toughness is meaningless late game. This balance doesn't apply to the helmet, chestplate, or boots of the respective sets so I assume it's a mistake.

**Comment by HIPPOKLEIDES** [comment]
reduced them to be less than or equal to vanilla armors (can't be in between as decimals are not acceptable for this). Also removed the toughness for steel to give diamond a slight advantage
