### ISSUE TITLE
Mob Behavior/Modded Foliage

### ISSUE THREAD

**Issue by Kalagath** [Conquest-Reforged/ConquestReforged#16]
You might already know this, but mobs are not able to properly pathfind through modded foliage blocks.
They just seem to be jumping around in one spot.
Also I think one should be able to break and retrieve blocks like grass, bushes and flowers by breaking them with shears rather than with an axe/pickaxe. That would be consistent with the Vanilla mechanics.
<3

**Comment by HIPPOKLEIDES** [comment]
Thanks for the report :). It's fixed now, so the tool for all of those blocks is shears and mobs can walk through modded plants. Many of the leaves are an exception however, as I need to extend certain classes to get the leaf mechanics working, and therefore can't change the pathfinding mechanic through those.
