### ISSUE TITLE
Tile roof incorrect recipe.

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#163]
Red tile roof can't be crafted because it crafts overgrown cobblestone.

![2018-05-02_18 41 57](https://user-images.githubusercontent.com/23204608/39554826-b1ff7174-4e3a-11e8-88d3-89b17a82b12f.png)

**Comment by HIPPOKLEIDES** [comment]
good catch. I've got it fixed now
