### ISSUE TITLE
empty ocean biome above sea level

### ISSUE THREAD

**Issue by Tobias0404** [Conquest-Reforged/ConquestReforged#166]
look 
![image](https://user-images.githubusercontent.com/38936371/39563613-3f3341bc-4eb1-11e8-8ce8-94a81585db4c.png)

**Comment by Tobias0404** [comment]
wrong picture
![2018-05-03_08 55 36](https://user-images.githubusercontent.com/38936371/39563632-504447d0-4eb1-11e8-831d-4c2cd579e8a0.png)

**Comment by CreativeRealms** [comment]
Should be fixed in 1.14.
