### ISSUE TITLE
Floating plant blocks

### ISSUE THREAD

**Issue by VolatilePotato** [Conquest-Reforged/ConquestReforged#169]
So in vanilla minecraft, if one breaks the bottom part of a 2 block high or more plant, all of it breaks to prevent floating plant blocks. If a block that has a plant on it is broken, the plant is broken also. I wish to see something like this happening in 1.12 conquest so that there are no weird floating plant blocks and makes it easier to clear out the foliage.

**Comment by HIPPOKLEIDES** [comment]
I'll keep this in mind for the future. However, I can't see this being the only option for plants as floating plant blocks can be valuable for some creative builders

**Comment by Burgersim** [comment]
Wanted to add to this, I would also love to see this, maybe just being able to enable or disable it via a config option? Because in creative I can see the reason to leavve the blocks floating, but when I play in survival with friends, I'd turn it off, so it seems more "natural".

**Comment by CreativeRealms** [comment]
Closed. Duplicate issue https://github.com/Conquest-Reforged/Indev/issues/183
