### ISSUE TITLE
Iron furnace

### ISSUE THREAD

**Issue by VolatilePotato** [Conquest-Reforged/ConquestReforged#170]
At the moment the iron furnace is not functional. I thought it would cook things much faster because it's an iron furnace but as soon as I put wood in to burn an oak log to produce charcoal, the two items disappeared but the furnace changed into a stone furnace from iron furnace all the while the two items inside vanished. When I mined the stone furnace, the two items that previously vanished popped out and I now had a stone furnace in my inventory instead, causing me to lose the 8 iron ingots that went into it.

**Comment by HIPPOKLEIDES** [comment]
Making the modded furnaces functional is on our to-do-list for the future. In the mean time, I taken away this broken functionality for the modded furnaces to prevent any more wasted materials.
