### ISSUE TITLE
1.12.2 Crash Report - Random Crashing, no idea what to do

### ISSUE THREAD

**Issue by Arcanusmc** [Conquest-Reforged/ConquestReforged#171]
[crash-2018-05-02_09.08.03-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/1973207/crash-2018-05-02_09.08.03-client.txt)

**Comment by HIPPOKLEIDES** [comment]
Looks like you're missing WorldEdit while trying to play with FAWE, so you'll have to either remove Worldedit or install FAWE (or reinstall if you're using the launcher).
