### ISSUE TITLE
World Edit issues

### ISSUE THREAD

**Issue by BuccaneerBeaver** [Conquest-Reforged/ConquestReforged#172]
Whenever i open the CR launcher the first singleplayer world i enter will have a working world edit. However if i go back to the main menu and then enter the world again world edit will stop working (i type whatever command but nothing will happen). In order to make it work again i must always re-open the launcher.

**Comment by HIPPOKLEIDES** [comment]
You might want to remove FAWE from the mods folder, as for some reason it's giving some people this issue.
