### ISSUE TITLE
World Converter 1.10.2 --> 1.12.2 issue

### ISSUE THREAD

**Issue by ano19920** [Conquest-Reforged/ConquestReforged#174]
I converted a 1.10.2 world to 1.12.2 using the world converter and everything with the ConquestReforged blocks worked out fine--------or so I **thought**.

It replaced DecoCraft2 blocks with any CR plants and things. It also turned some kind of block into glass bottles decorations. I use PlaceableItems so that I can put such items down as decor, which is how thatʻs able to even do that. But now... there are glass bottles ALL OVER THE PLACE?? Maybe an entity was there or some kind of flower was there? I really have no clue. Also, it turned some other plants (I assume) into CHEESE? It also turned fruit on trees from Pamʻs HarvestCraft into trapdoors.

I shouldʻve backed up my world, I guess. LOL [[editted to add more screenshots of some of the weird stuff]]
![image](https://user-images.githubusercontent.com/23690411/39659798-a7b79274-4ff6-11e8-851b-c482b843ce31.png) 
![image](https://user-images.githubusercontent.com/23690411/39659801-b916f74e-4ff6-11e8-8012-7547a58b642d.png) 
![image](https://user-images.githubusercontent.com/23690411/39659815-d9f4c31a-4ff6-11e8-9ff8-c9273b186221.png) 
![image](https://user-images.githubusercontent.com/23690411/39659831-08ca614a-4ff7-11e8-9f87-0bc8bfa511c5.png)
![image](https://user-images.githubusercontent.com/23690411/39659854-abc4fa86-4ff7-11e8-9d8c-20bae72ce84a.png)
![image](https://user-images.githubusercontent.com/23690411/39659856-b8c0a06e-4ff7-11e8-874c-c2795213aa71.png)
![image](https://user-images.githubusercontent.com/23690411/39659860-c0032b26-4ff7-11e8-90c5-afdb78dc8cbd.png)

**Comment by HIPPOKLEIDES** [comment]
I'm afraid the converter isn't designed to work with other mods. However, you can try going into the converter files and replacing the level.dat file made from a fresh world in 1.12 and your own mappings.json if certain conversions still give you trouble.

**Comment by dags-** [comment]
just to add, the converter doesn't mess with the original world, it saves the converted files to a new folder so your 1.10.2 world is fine (unless you deleted it, or opened it in 1.12)
