### ISSUE TITLE
Buzzsaw and Elven Compass have same recipe

### ISSUE THREAD

**Issue by Elnariz** [Conquest-Reforged/ConquestReforged#179]
Hi, The buzzsaw and elven compass have the same recipe. When trying to create the buzzsaw, the outcome is the elven compass. This is in survival, seems to work fine in creative in the crafting table. (edit for more detail)

Thanks for the mod and patience :)
![buzzsaw](https://user-images.githubusercontent.com/39007127/39663976-16f30d96-504a-11e8-93bf-3ef67530d5e1.png)

**Comment by HIPPOKLEIDES** [comment]
fixed, thanks
