### ISSUE TITLE
hello, when hitting the cat tails 3 blocks high, is it not better to make it hapen that if you hit the bottom one that it also break the other 2?

### ISSUE THREAD

**Issue by Loudim** [Conquest-Reforged/ConquestReforged#18]

**Comment by HIPPOKLEIDES** [comment]
maybe something to consider in 1.13

**Comment by CreativeRealms** [comment]
Dev note: Find a way to change plant functionality between survival/creative mode so plants don't float in survival but do so in creative for building purposes. Should be prioritized for 1.14.
