### ISSUE TITLE
Campfire crashes the game when inserted in crafting table

### ISSUE THREAD

**Issue by Elnariz** [Conquest-Reforged/ConquestReforged#180]
Hi,

Here is the crash log that happens when inserting the campfire in the crafting table.

The game crashed whilst rendering screen
Error: java.lang.ArrayIndexOutOfBoundsException: 32767

Thanks

**Comment by HIPPOKLEIDES** [comment]
Need the full crash-log, doesn't seem like it's actually the campfire as I can't recreate a crash with it

**Comment by Elnariz** [comment]
Tried to get the crash log, wasn't able to. Optifine and forge weren't the latest versions, updated it. No more crashes. Ticket can be closed. Thank you for looking into it.
