### ISSUE TITLE
[Bug] Wheat & Farmland Issues

### ISSUE THREAD

**Issue by Kranchan** [Conquest-Reforged/ConquestReforged#181]
The Big Wheat Crop and Normal Wheat Crop is growable on everything. I don't know if this is intentional.

https://i.imgur.com/kulftg9.png

The Normal Wheat Crop has strange blue and red dots on the texture.

https://i.imgur.com/NGBJtyO.png

I am unable to plant any vanilla MC crops onto CR Farmland.

**Comment by HIPPOKLEIDES** [comment]
1 and 2 are intentional

**Comment by Kranchan** [comment]
What is the reasoning behind 2?

**Comment by CreativeRealms** [comment]
Because vanilla blocks can't get changed so they only work as intended in vanilla.
