### ISSUE TITLE
Block 270:8

### ISSUE THREAD

**Issue by talset333** [Conquest-Reforged/ConquestReforged#185]
Block 270:8 is some sort of blue wallpaper block (without the ornaments). It has no name, no block variants and is shown as a green placeholder block in the hand & inventory

**Comment by talset333** [comment]
same with 270:12

**Comment by HIPPOKLEIDES** [comment]
Old blocks that were moved to the 1.12 concrete blocks. If the green placeholders annoy you, there's an issue where liteloader conflicts with our filter (placeholders will be gone in 1.13 anyway)
