### ISSUE TITLE
Crafting Recipe Broken - Workbench 

### ISSUE THREAD

**Issue by StickerQueen** [Conquest-Reforged/ConquestReforged#188]
Crafting recipe for workbench does not work. The recipe involves an empty rack with a missing texture (as shown in the picture below). Attempting this recipe with a normal empty rack (with the normal texture) does not work.

![image](https://user-images.githubusercontent.com/33881998/39679371-70bbf4a0-5194-11e8-838a-abe519d1e74f.png)

**Comment by HIPPOKLEIDES** [comment]
fixed, thanks
