### ISSUE TITLE
Growing tree replaces nearby blokcs

### ISSUE THREAD

**Issue by DirtyNative** [Conquest-Reforged/ConquestReforged#193]
When a tree is growing, it replaces some blocks which are nearby that tree.
![2018-05-07_20 35 25](https://user-images.githubusercontent.com/10748827/39718499-c284159a-5236-11e8-9cd6-eb92b3af0ff8.jpg)
![2018-05-07_20 35 32](https://user-images.githubusercontent.com/10748827/39718500-c2a58c5c-5236-11e8-99c8-3db151a07a35.jpg)

This makes tree farms completly useless

**Comment by HIPPOKLEIDES** [comment]
duplicate of #65

**Comment by DirtyNative** [comment]
Will this ever get fixed?

**Comment by CreativeRealms** [comment]
This will be fixed in 1.15.2.
