### ISSUE TITLE
New Huge Realistic Oceans - Suggestion

### ISSUE THREAD

**Issue by MedievalPigeon213** [Conquest-Reforged/ConquestReforged#194]
It would be cool if the oceans were more earthlike and massive. With a few islands dotted in the waters with continents.

https://www.google.ca/search?q=earth&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjUuqHYgvXaAhUSS2MKHaT3BDEQ_AUoAXoECAAQAw&biw=2400&bih=1204#imgrc=bOtki--Qq9tNKM:

**Comment by CreativeRealms** [comment]
Will be configurable in 1.14.
