### ISSUE TITLE
Finding Mud

### ISSUE THREAD

**Issue by COWLISSE** [Conquest-Reforged/ConquestReforged#198]
Hey! After searching for hours for Mud in survival and in creative mod, walked at least 50k blocks, i've never find any Mud (The orangish one, "Mud Block" not muddy dirt or else). I went through the mod codes and it looks like it's very rare in some Swamp but after hours of searching, none... Can someone confirms me that it exists? It really bothers me for my build.

**Comment by lungora** [comment]
If it were craftable from say: dirt and clay, or dirt and dark mud, or dirt and water. That'd be a good useful fix, and rather historic since everyone everywhere made mud brick houses.

**Comment by HIPPOKLEIDES** [comment]
You can get a decent amount at the marsh biome. In the future, there will be additional methods of obtaining mud
