### ISSUE TITLE
Connected Texture not working on CR 3.0.0

### ISSUE THREAD

**Issue by SamMadeChannel** [Conquest-Reforged/ConquestReforged#2]
**How to reproduce**
Taken from Patreon tier 3 reward posts:

- Add ConquestReforged-3.0.0-mc1.12.2.jar to _mods_ folder
- Add OptiFine_1.12.2_HD_U_C6.jar to _mods_ folder
- Add conquest_reforged_dev.zip to _resourcepacks_ folder
- Set Connected Textures to _Fancy_
- Load a world (any world, tested 2-3 newly generated and existing savegames from older versions)
- Enable ConquestOfTheSun shaders but i doubt it's related.

**Observed**
No texture connects (every block repeats itself)
![2018-02-06_20 20 54](https://user-images.githubusercontent.com/36215122/35894365-47544176-0b80-11e8-8bb4-6df5f2717916.png)

**Expected**
Connected textures

**Comment by HIPPOKLEIDES** [comment]
Have you tried running Optifine C8 (the latest release) or C7 for 1.12.2?

**Comment by wunder-bread** [comment]
Verified `ConquestReforged-3.0.0-mc1.12.2` + `OptiFine_1.12.2_HD_U_C8` connected textures are working fine.
![2018-02-08_11 31 02](https://user-images.githubusercontent.com/17827326/35985012-a2112d24-0cc3-11e8-8fa6-0402ebae9409.png)
