### ISSUE TITLE
Slate variants use frozen cobblestone

### ISSUE THREAD

**Issue by ItsCestial** [Conquest-Reforged/ConquestReforged#200]
![0tmqro7](https://user-images.githubusercontent.com/38892324/39783850-4283286e-52cb-11e8-9082-00f11d157279.png)
![gebewzy](https://user-images.githubusercontent.com/38892324/39787133-b4aa7606-52d8-11e8-833b-6ea7f00d0ed1.png)

**Comment by HIPPOKLEIDES** [comment]
fixed, thanks
