### ISSUE TITLE
Conquest Dirt - Variety of issues.

### ISSUE THREAD

**Issue by lungora** [Conquest-Reforged/ConquestReforged#204]
1: it has no visible different in the inventory without enabling debug item names to tooltip.

2: it cannot be crafted back into regular minecraft dirt.

3: both conquest dirt and minecraft dirt have seperate crafting uses, with the second used for dirty fishscale the the first everything else - this is unintuative.

**Comment by HIPPOKLEIDES** [comment]
At this point, might it be worth it to just switch coarse dirt (the dirt+grass texture) with the conquest dirt in the future?

**Comment by CreativeRealms** [comment]
Fixed in 1.15.2.
