### ISSUE TITLE
Keep Items In Crafting Table

### ISSUE THREAD

**Issue by GUCCIDEAN** [Conquest-Reforged/ConquestReforged#207]
Would be nice if items stayed in the crafting table, for eg. when crafting stucco you need buckets of water and its a pain to go in and out the crafting table and having to place all the items in the right order again every single time

**Comment by HIPPOKLEIDES** [comment]
You might want to check out https://minecraft.curseforge.com/projects/portable-crafting

In any case, I don't see us implementing this in the CR mod itself when other mods do it already
