### ISSUE TITLE
Rough granite variations crafted with serpentinite instead of rough granite

### ISSUE THREAD

**Issue by ItsCestial** [Conquest-Reforged/ConquestReforged#208]
![hgnluxl](https://user-images.githubusercontent.com/38892324/39846857-dce0486e-53b2-11e8-9d8f-35d4b3dc42cf.png)
![2ijfo5i](https://user-images.githubusercontent.com/38892324/39846858-def1ba34-53b2-11e8-8cfc-04bb4959f833.png)
![54hktps](https://user-images.githubusercontent.com/38892324/39846862-e25c1098-53b2-11e8-951f-316e9fa15841.png)
![zpo4h3z](https://user-images.githubusercontent.com/38892324/39846863-e388d9ba-53b2-11e8-96ba-4b3c5df68d2c.png)

**Comment by HIPPOKLEIDES** [comment]
fixed, thanks
