### ISSUE TITLE
Once a paintbrush loses durability it stops being able to be used

### ISSUE THREAD

**Issue by lungora** [Conquest-Reforged/ConquestReforged#209]
![2018-05-10_17 15 02](https://user-images.githubusercontent.com/932293/39865059-e8d42014-5475-11e8-90ae-268b6255b645.png)

As you can see, I used two paintbrushes' initial charges to paint one red plaster each, but the recipe no longer works.

**Comment by HIPPOKLEIDES** [comment]
should be fixed for the paint brush recipes now, thanks
