### ISSUE TITLE
Word Edit tools and Schemes Glitches

### ISSUE THREAD

**Issue by Ruteno** [Conquest-Reforged/ConquestReforged#211]
When you leave a world (save game) and open other (or the same) you must to rename the tools to use "world edit"... so the tools doesn't work... You must to close the game, run the game, and open a new world, and now when you rename the "world edit" tools will work... Every time you need to change the world you must do this with the tools...  Same problem with the schemes... save a schem in one world, when you close the world and change to other one to paste the schem, the commands doesn1t work... you must repeat all the process... close the game, run it again, and then, you can load and paste the scheme...

renamed tools as: farwand / Replace tool / pos1 / pos2 / and other tools not work if you get out of a world to enter on other one... Also happens with the commands schem load and paste...

Must be other glitches abaut the "world edit" and the commands, but until now i just see these...

Sorry abaut my english i"m not native... and i hope you understand...

Thanks...

**Comment by HIPPOKLEIDES** [comment]
These seem like issues with Worldedit/FAWE rather than CR.

If you're using FAWE go here: https://github.com/boy0001/FastAsyncWorldedit/releases
If you're using Worldedit go here: https://github.com/sk89q/WorldEdit
