### ISSUE TITLE
MC 1.12.2 - Crash During World Creation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Conquest-Reforged/ConquestReforged#212]
Crash Log
https://paste.dimdev.org/vasavabifa.txt

Additional Information
https://gist.github.com/P3rf3ctXZer0/7f6bd7ad828a69677ee18fa8e9bb2a5b

**Comment by HIPPOKLEIDES** [comment]
Remove ReccurentComplex if you want to generate worlds with CR. A fix requires a big factor, which isn't really worth doing until 1.13
