### ISSUE TITLE
Connected textures for Elven and Dwarven pillars not working

### ISSUE THREAD

**Issue by Vitsukal** [Conquest-Reforged/ConquestReforged#214]
It appears that the connected textures on these pillars (possibly others, I haven't checked them) are not working.  I have the same settings enabled as when I was using the 1.10 version of Conquest and they are not stacking in a connected texture as they did in the previous version.

**Comment by HIPPOKLEIDES** [comment]
I can't seem to recreate this. You might be able to hit f3+t to remedy the issue, or start a fresh world.
