### ISSUE TITLE
Too many rocks when harvesting stone

### ISSUE THREAD

**Issue by Rabenweis** [Conquest-Reforged/ConquestReforged#217]
The amount of rocks should be drstically reduced when mining stoneblocks. After a while my inventory is absolutely filled with them. They're nice for decoration here and there, but not in that great amount. Half as much or maybe even a quarter would be enough.

**Comment by HIPPOKLEIDES** [comment]
There will likely be more mechanics with the rocks in the future, so I'm going to keep them as there are now rather than continue to go back and forth changing their drop rates.
