### ISSUE TITLE
Vertical carved sprice is too expensive

### ISSUE THREAD

**Issue by Rabenweis** [Conquest-Reforged/ConquestReforged#218]
The vertically carved spruce blocks needs a chisel and three spruce log blocks and yields one carved block as a result. Is that supposed to be like that? I think, this is a bug

**Comment by HIPPOKLEIDES** [comment]
"Carved Spruce Wood" requires 1 spruce log. "Horizontal Carved Spruce" requires 3, on the other hand. I fixed the Horizontal Carved Spruce to give back three items
