### ISSUE TITLE
Suggestion - Planters

### ISSUE THREAD

**Issue by Kranchan** [Conquest-Reforged/ConquestReforged#22]
Planters similar to the ones found in Garden Stuff would be a nice addition. The top edge on some should expand to take up the entire cube so that you can put ivy on the sides.

Garden Stuff Mod example. Specifically the marble urns. https://media.forgecdn.net/attachments/17/291/scrcontainers.png

Ivy example. https://cdn.gardenista.com/wp-content/uploads/2015/04/fields/Terrazzino-Garden-Urns-Gardenista-584x438.jpg

General examples.
https://upload.wikimedia.org/wikipedia/commons/d/d0/Smithsonian-haupt-garden-urn.jpg
http://www.landscaperoutlet.com/images/campania/m/7232457.jpg

**Comment by CreativeRealms** [comment]
Added in 1.15.2.
