### ISSUE TITLE
[Suggestion] Ability to use vanilla minecraft worlds

### ISSUE THREAD

**Issue by Rabenweis** [Conquest-Reforged/ConquestReforged#221]
Now, I don't anyone to misunderstand my intentions here. I think, the worlds created by the Conquest world generator are beautiful and they create a whole new experience in minecraft. But I really would like to be able to use all the possibilities of conquest in my familiar minecraft world. I just copied my vanilla world into the conquest folder and was able to load it no problem and I improved many of my old builings with the conquest stuff, but as soon as I roamed around, I noticed, that the world generation of conquest clashed with the old map. Using the same seed yielded a totally different world, no matter, what world generation I used.

I'm aware, that this feature would strip me of many of the new materials, safe from the occasional chest finding, but as I additional option I would really appreciate it.

**Comment by CreativeRealms** [comment]
World generator won't override vanilla terrain in 1.14.
