### ISSUE TITLE
Villagers not planting seeds 

### ISSUE THREAD

**Issue by DirtyNative** [Conquest-Reforged/ConquestReforged#223]
I made a testmap, created a village and summoned one villager into a wheatfield. As the wheat grows to maximum size, the villager started to harvest. But there is a issue, the villager does not pick up the seeds or the wheat. Even if I throw bread, carrots, etc. to a fresh  summoned villager, he is not picking up anything. 

Tested with version 3.0.1

**Comment by HIPPOKLEIDES** [comment]
Same thing with the minecart, this is an area we haven't edited or added onto, so it may be another mod acting up, forge itself, or a server causing it
