### ISSUE TITLE
Cannot join single player world after playing on a multiplayer server

### ISSUE THREAD

**Issue by LunarDrift** [Conquest-Reforged/ConquestReforged#224]
Whenever I try to play a single player world after playing online, it will say "Loading World" for a split second and then the screen will go blank.
![capture1](https://user-images.githubusercontent.com/39462979/40280563-088fdff4-5c1b-11e8-9f13-da8b40eeac8e.PNG)

Here's a pastebin of the Messages and Errors log. Couldn't paste the whole thing so hopefully this is enough info for you. https://pastebin.com/7JU9Zk7Z

**Comment by HIPPOKLEIDES** [comment]
looks like something with worldedit cui from the log but could be wrong. Anyway, this shouldn't be a problem with CR
