### ISSUE TITLE
Ore Generation, Texture Pack, World Lag [Question & Issue]

### ISSUE THREAD

**Issue by aaronegger** [Conquest-Reforged/ConquestReforged#226]
Hi,

i am using this mod (ConquestReforged-3.0.1-mc1.12.2) to play it in survival mode.
It creates a beautiful landscape, and i transfered all my items for my old map to the newly generated one (using Conquest Reforged).
I have already built my home and other things and now started to mine for ores but i cant find anything :(

I also couldnt find any wiki or other information site that gives me infos about that.
The only thing i found was "Ore generation tweaked for larger but rarer deposits". But this is not helpful at all...

Is there some kind of documentation that shows where which ore is being generated?

And i am also facing an issue if i run around the world. The server logs a lot of "Conquest Reforged loaded a new chunk (x, z Dimension: 0) during chunk population, causing cascading worldgen lag".

And the last point I would like to know if there is a texture package with higher resolution (e.g. 128x128)? Maybe a paid package?

But apart from the ore generation i am very happy with this mod :)
It looks much better and more dynamic than vanilla mc!
Thank you guys for this great mod :+1:

**Comment by HIPPOKLEIDES** [comment]
"Conquest Reforged loaded a new chunk (x, z Dimension: 0) during chunk population, causing cascading worldgen lag" just means you might lag a bit while generating the world. 

There is no wiki at the moment.

I don't see Monsterfish doing a higher resolution pack with the amount of textures that have been done.

Glad to hear you are enjoying the mod though :)
