### ISSUE TITLE
Blue Wood texture bug

### ISSUE THREAD

**Issue by Alakabam** [Conquest-Reforged/ConquestReforged#228]
Every blue wood texture turns out to be weathered even when the name suggests/ toolbar picture suggests it's a full color instead of a weathered one. The only one that seems to work is the Cyan colored wood. 

![2018-05-27_10 42 22](https://user-images.githubusercontent.com/39667656/40584066-f4a11ca8-619a-11e8-82a9-c06194985d3d.png)

& 

![2018-05-27_10 45 38](https://user-images.githubusercontent.com/39667656/40584076-25b23db8-619b-11e8-9059-4be8e2715263.png)

**Comment by CreativeRealms** [comment]
Fixed in 1.15.2.
