### ISSUE TITLE
Conquest chest should have storage functionality

### ISSUE THREAD

**Issue by MikeyView** [Conquest-Reforged/ConquestReforged#229]
It feels weird to me that chest which, thanks to 3d model, look even more like chest doesn't have storage funcionality. Thanks to that, people start using this more often (thanks to functionality other than just decorative). I know you are very busy, but I'm think this "bug" can be easily fixed. 
![image](https://user-images.githubusercontent.com/39678193/40589819-ec9aa60a-61f4-11e8-9ca0-88bbc52abafa.png)

**Comment by CreativeRealms** [comment]
Closing since survival won't be a thing for a long time.
