### ISSUE TITLE
Mod Conflict (Electroblobs Wizardry)

### ISSUE THREAD

**Issue by imladris3000** [Conquest-Reforged/ConquestReforged#231]
I have found a mod conflict between Conquest Reforged and Electroblobs Wizardry. What happens is that when holding a Wizardry wand there appears a black square around your reticle obscuring a small space of your screen. To be sure of this conflict I made a test world with nothing but conquest, wizardry and jei.

**Comment by dags-** [comment]
we don't do any rendering other than in inventory ui's
