### ISSUE TITLE
Crash on inventory with Bibliocraft

### ISSUE THREAD

**Issue by Ajakkk** [Conquest-Reforged/ConquestReforged#232]
Clients crash when they open CR search via hotkey. We spoke on Discord, here's the crash-report.

[crash-2018-06-02_23.19.49-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2065465/crash-2018-06-02_23.19.49-client.txt)

Something else I'm curious about is if these images look correct. I'm using ConquestReforged-3.0.2-mc1.12.2 and OptiFine_1.12.2_HD_U_D3 and the resource pack posted [here.](https://www.curseforge.com/minecraft/texture-packs/conquest-reforged-resource-pack) The torches and redstone torches have these weird square looking affects and the menu contrast vs the text is non-existent. I also have the green texture issue on JEI but I saw that there is a fix for that somewhere, I can look for that.

![2018-06-02_23 51 51](https://user-images.githubusercontent.com/20494241/40881518-62f52346-66c0-11e8-830a-aee4536a55eb.png)
![2018-06-02_23 52 01](https://user-images.githubusercontent.com/20494241/40881519-630cc726-66c0-11e8-9970-13b470db149b.png)

Kind regards, awesome mod, cheers.

**Comment by dags-** [comment]
eugh, I'll add a catch for this

**Comment by Applejakerie** [comment]
I wonder if the textures are down to an Optifine setting.

**Comment by HIPPOKLEIDES** [comment]
With regards to the torch and redstone candle, it seems like something else is overriding our custom models for those two blocks (thus making you see those parts of the texture that aren't normally mapped to those areas)

**Comment by Applejakerie** [comment]
With ConquestReforged-3.0.2-mc1.12.2, the redstone torch looks like above but the normal torch is unaffected, looking fine. When Optifine and the resource pack posted [here](https://www.curseforge.com/minecraft/texture-packs/conquest-reforged-resource-pack) is used as well then both the redstone torch and the normal torch have the weird texture affect. If all 3 of those are not in use, the redstone torch and normal torch are both very much vanilla textures, no changes.

Any ideas on how I could find out what it is that is overriding these textures considering they are not showing with CR, Optifine and CR's resource pack removed?

**Comment by Applejakerie** [comment]
With only Conquest loaded, the normal torches look fine, the redstone torches have the weird texture look as shown above. With Conquest and the resource pack with and without Optifine, both torches have the weird texture look as shown above. I've just confirmed that, there's definitely nothing else overlapping the texture, not from another mod anyways. The limestone rocks work fine, so there is a mod conflicting with that. I'll look into which later today.

**Comment by Yaminara** [comment]
In the end you managed to fix the torch error?. It looks the same to me, I have the same problem.
