### ISSUE TITLE
Crash when breaking limestone rocks.

### ISSUE THREAD

**Issue by Applejakerie** [Conquest-Reforged/ConquestReforged#233]
If you place and then try to break a limestone rock, the client crashes. Not sure if this will also translate over to the other similar rock block types. Not willing to try and we now can't remove the block. ^^;

[crash-2018-06-03_23.26.16-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2066428/crash-2018-06-03_23.26.16-client.txt)

**Comment by dags-** [comment]
Doesn't appear to be anything conquest related. You've got a number of coremods present, I'd look first at each of those

**Comment by Applejakerie** [comment]
Yeah I'll look into it and update to let you know which is causing issues with CR.
Thanks anyways.
