### ISSUE TITLE
Flint Rarity issue and other suggestions!

### ISSUE THREAD

**Issue by HiveHD** [Conquest-Reforged/ConquestReforged#236]
**First things first,** 

Flint is super rare in survival using the mod and conquest biomes currently. Gravel is pretty much non-existent in most biomes and the dirt drop rate is very uncommon (I just tested it and destroyed 300 dirt blocks and only got 1 flint) this paired with the fact most ground blocks arent actually 'dirt' but a mixture of other blocks makes it even harder to find flint. 

I greatly approve of the flint idea and never enjoyed the concept of having to unrealistically punch a tree down to make wooden tools. But as it stands ive not managed to have an enjoyable conquest reforged survival experience because early game is so tedious.

**now for the suggestions:**

a config is the major suggestion! a simple config file with the ability to toggle some options so different people can customise their experience to their preference. These are both my personal opinions but mostly opinions and suggestions ive seen from multiple other players on this github.

1) Be able to toggle on the destruction of the base of a plant destroying the rest of it! (bamboom forests are a pain to clear out, floating bamboo everywhere!) (I understand floating plants are used in a lot of creative builds so the option to toggle this to preference would be perfect)

2) Control flint droprate

3) Be able to toggle whether or not you can walk through leaf blocks

4) For some reason (not sure if this is intended) conquest generated trees appear even when using the vanilla biome generation. This is annoying when trying to avoid trees that dont provide direct logs (conquest trees use log slabs and other blocks). (especially when using Dynamic Trees Mod)

[In regards to the Dynamic Trees Mod, I think this would work perfectly with conquest and actually looks better than the conquest generated trees as they have tapered trunk models and 3D branches that can be cut back and trimmed, etc. maybe some kind of integration or support.] [https://minecraft.curseforge.com/projects/dynamictrees]

**Comment by MikeyView** [comment]
About that flint issue I don't have any problem. For me it drops like 2-3 per 10 dirt blocks. So maybe other mod collide with conquest?

**Comment by CreativeRealms** [comment]
Will be fixed in 1.14.

**Comment by CreativeRealms** [comment]
Will be fixed in 1.15.2.
