### ISSUE TITLE
Board Blocks Turn See-Through when a block placed on top of them

### ISSUE THREAD

**Issue by BurnMyChildren** [Conquest-Reforged/ConquestReforged#240]
Exactly what the title says, happens with full blocks only, trapdoors and 3dmodels (barrel etc) works fine when placed on top
![2018-06-11_13 30 00](https://user-images.githubusercontent.com/40210127/41301976-29e8752a-6e1e-11e8-9700-c07b23d72677.png)
![2018-06-11_13 30 05](https://user-images.githubusercontent.com/40210127/41301977-29f8b2b4-6e1e-11e8-9809-3288d11defab.png)

**Comment by CreativeRealms** [comment]
Fixed in the next update.
