### ISSUE TITLE
[Suggestion] Oredict Ingots, Blocks, Nuggets

### ISSUE THREAD

**Issue by Burgersim** [Conquest-Reforged/ConquestReforged#241]
Love this mod, just wanted to ask if this would be possible. I'm playing survival with friends and we like Spartan Weaponry and Shields, which looks at the OreDict to register e.g. Bronze and Steel Weapons and Shields, but it seems the Ingots are not OreDicted in this mod, which is a shame for compatibility.

Thanks in advance (also posted a comment on curseforge, but thought this would probably be a better place to suggest this feature)

**Comment by CreativeRealms** [comment]
Irrelevant in 1.15.
