### ISSUE TITLE
Spruce logs and Conquest Spruce are used in different recipes

### ISSUE THREAD

**Issue by MikeyView** [Conquest-Reforged/ConquestReforged#242]
In the topic I mean that we have 2 different spruce logs: the vanilla (minecraft:log) and the conquest version (conquest:wood_full_1) but you use only the vanilla one for crafting eg. Spruce beam. Yet in conquest world generator the spruce saplings and naturally generated spruce trees drops conquest spruce logs. That's mean I can't make spruce beam without using commands.
![image](https://user-images.githubusercontent.com/39678193/41502657-89f82d62-71bf-11e8-86cb-cbdf82326845.png)

**Comment by CreativeRealms** [comment]
Recipes will be redone in 1.14.
