### ISSUE TITLE
Cannot Download 1.10.2 Version

### ISSUE THREAD

**Issue by Fhweo** [Conquest-Reforged/ConquestReforged#243]
Can't download the 1.10.2 version, I press launch, login, & select the features. It says "collecting assets to download", then ends with an error message.

sun.security.validator.VAlidatorException: PKIX path buildinng failed:
sun.security.provider.certpath.SunCertPathBuilderException:
unable to find valid certification path to requested target

To report this error, please provide:
[Crash.Report.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2110345/Crash.Report.txt)

**Comment by dags-** [comment]
You're probably better off getting the mod off curse and installing it manually if you want to stay on old versions
