### ISSUE TITLE
1.12 - Color Pallette Shows Infinite nones

### ISSUE THREAD

**Issue by spinach80186** [Conquest-Reforged/ConquestReforged#244]
![screenshot 2](https://user-images.githubusercontent.com/38845127/41632817-c429cfb2-7409-11e8-9455-7f589bba1c91.png)

As you can see, there is a massive loop of green boxes around the 'Magenta Shulker Box' ID 221:1 (Also, the Magenta Shulker Box does look like a wooden box, not sure if it is supposed to).

**Comment by dags-** [comment]
The block's model probably doesn't have the correct particle texture so the palette is matching the green 'none' texture with all the other 'none' blocks

**Comment by CreativeRealms** [comment]
Green blocks won't exist in 1.14.
