### ISSUE TITLE
Birds nest Recipe bug?

### ISSUE THREAD

**Issue by SebbePwnYou** [Conquest-Reforged/ConquestReforged#246]
Just take a look at the Picture / Gif and tell me whats wrong :)

https://i.gyazo.com/2dc07044aaee824e3814ea0d45abb9b9.mp4

https://i.gyazo.com/9d0eb6f503920a51b72bd20cc4f6c27b.png

**Comment by CreativeRealms** [comment]
Recipes will be redone in 1.14.
