### ISSUE TITLE
[Suggestion] Have cobblestone (and other) walls with "spikes"

### ISSUE THREAD

**Issue by Rabenweis** [Conquest-Reforged/ConquestReforged#247]
In vanilla minecraft, when you build the cobblestone walls directly next to another block, they formed a pillar, that was a little bit higher than the wall itself. In conquest, these are gone now, because the wall segment is as high as the pillar. IOn some circumstances I really liked the look of these pillars. Maybe we can have a way to get them back? Maybe have another kind of wall?

**Comment by CreativeRealms** [comment]
Those will not be added due to a design decision. You might be able to change the model manually by removing the modified files.
