### ISSUE TITLE
[Crashing] Block tesselation crash caused by block wall models

### ISSUE THREAD

**Issue by GuusLieben** [Conquest-Reforged/ConquestReforged#248]
This issue has popped up for several players on both SP & MP. When rendering a chunk from converted worlds with a block wall model this crashes the client, though the server remains unharmed. This issue persists also after restarting the client. This doesn't seem to be related to any graphics driver issue, as people with different gpu's and driver versions are experiencing this issue (verified from Intel Integrated Graphics to GTX1080 gpu's).

I have attached several crashlogs, and will of course be available for any testing.

The issue seems to be related to the model, rather than blocktype, as the crash occurs for anything from wood to stone type walls.

[crash-2018-06-26_14.52.34-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140254/crash-2018-06-26_14.52.34-client.txt)
[crash-2018-06-26_15.39.13-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140255/crash-2018-06-26_15.39.13-client.txt)
[crash-2018-06-06_09.03.01-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140256/crash-2018-06-06_09.03.01-client.txt)
[crash-2018-06-06_17.26.47-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140257/crash-2018-06-06_17.26.47-client.txt)
[crash-2018-06-06_17.32.41-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140258/crash-2018-06-06_17.32.41-client.txt)
[crash-2018-06-06_17.36.14-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140259/crash-2018-06-06_17.36.14-client.txt)
[crash-2018-06-06_17.39.15-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140260/crash-2018-06-06_17.39.15-client.txt)
[crash-2018-06-06_17.44.34-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140261/crash-2018-06-06_17.44.34-client.txt)
[crash-2018-06-26_20.56.04-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/2140273/crash-2018-06-26_20.56.04-client.txt)

**Comment by HIPPOKLEIDES** [comment]
Has anyone tried updating Optifine? It looks like everyone in those crash-logs was using Optifine D1, and Optifine is known to mess with all this graphics related stuff.

**Comment by guuslieben** [comment]
Updating to OptiFine E1 does indeed fix the crashing. Though it seems a texture issue appears with E1, the reinforced doors take the texture of white/green windows (see screenshot)

![image](https://user-images.githubusercontent.com/10957963/41981481-52e36c48-7a29-11e8-8b90-03342d75f72b.png)

**Comment by guuslieben** [comment]
+1, rope rail looking like this

![image](https://user-images.githubusercontent.com/10957963/41981674-c3851654-7a29-11e8-98e6-f988eabf0879.png)

**Comment by guuslieben** [comment]
Also found some texture glitches with the taiga forest floor and rope rails, so I suppose E1 isn't perfect for it either

**Comment by HIPPOKLEIDES** [comment]
I looked at all of those blocks, and they're fine with Optifine E1 in a converted world. This has to be an issue with the world's ids being shifted, or you were in old worlds and need to restart MC

**Comment by guuslieben** [comment]
Probably a restart will do, this was taken at the Hub on Darwin Reforged, so I can personally verify the ID's on that end are fine ✌🏼
-DiggyNevs

**Comment by guuslieben** [comment]
@HIPPOKLEIDES Restarting the client again fixed all 'glitches'. So this can be closed ✌️

**Comment by guuslieben** [comment]
Received reports from Loudim that this issue has not been fixed for other clients with other OptiFine versions.
