### ISSUE TITLE
Several items such as "item.lime.name" are missing textures and UI and recipe

### ISSUE THREAD

**Issue by AlphaWolf777** [Conquest-Reforged/ConquestReforged#25]
Several items in the misc category such as one called "item.lime.name" are missing textures and UI. They can be accessed in creative mode under the misc items tab, but they don't show up in survival.

**Comment by HIPPOKLEIDES** [comment]
Lime has been removed. I also just finished up the lang file. As for the textures, just waiting on a few more ;)
