### ISSUE TITLE
Wooden Trapdoor to expensive

### ISSUE THREAD

**Issue by Rabenweis** [Conquest-Reforged/ConquestReforged#250]
Because a Wooden Trapdoor needs three Metal Grates and each Metal Grate needs three iron ingots, a set of six Wooden Trapdoors needs nine iron ingots. Granted, it's not the most expensive thing on the menu, but I still think it's to much. Make the recipe just require one Metal grate, perhaps? Or Let it yield 16 Trapdoors?

**Comment by CreativeRealms** [comment]
Recipes will be redone in 1.14.
