### ISSUE TITLE
Ascending east/west powered rail has the wrong model when powered

### ISSUE THREAD

**Issue by Biotronic** [Conquest-Reforged/ConquestReforged#254]
Powered rails look right when power is not applied, but the moment they get a Redstone signal, the ones going east->west or west->east have the wrong model - the east->west one uses the west->east model, and vice versa.

[Screenshots demonstrating issue.](https://imgur.com/a/I3IQAqO)

This issue exists in both the 1.10.2 and the 1.12.2 version of CR.

How to reproduce:

On a flat surface, place a Redstone Block.

On top of the Redstone Block, place 1 rail of any kind.

Directly east and west (x plus/minus 1) of the Redstone Block, place 1 powered rail.

Notice that rails [point in the wrong direction](https://i.imgur.com/QNNIUXf.png).

Order of placement does not appear to matter, except you need to place the Redstone Block before putting the rail on top of it. :p

**Comment by aaronegger** [comment]
I have this issue too :+1:

**Comment by aaronegger** [comment]
I have a fix for this issue:

Extract the jar file of the mod.
Then go to \ConquestReforged-3.0.1-mc1.12.2\assets\minecraft\blockstates
Open the file "golden_rail.json" (with any text editor).

Replace these lines:
        "powered=true,shape=ascending_west": { "model": "golden_rail_active_raised_ne", "y": 90 },
        "powered=true,shape=ascending_east": { "model": "golden_rail_active_raised_ne", "y": 270 },

With these:
        "powered=true,shape=ascending_west": { "model": "golden_rail_active_raised_ne", "y": 270 },
        "powered=true,shape=ascending_east": { "model": "golden_rail_active_raised_ne", "y": 90 },

Save it and open the jar file with 7zip or another container editor.
Go to the same subfolder (\ConquestReforged-3.0.1-mc1.12.2\assets\minecraft\blockstates)
and copy the edited file ("golden_rail.json") into this folder.

Sorry for my bad description. Hope this helps.

**Comment by CreativeRealms** [comment]
Fixed in the latest update.
