### ISSUE TITLE
[Request] Shark texture for dolphin model!

### ISSUE THREAD

**Issue by worldwideguy** [Conquest-Reforged/ConquestReforged#264]
You know this is an almost "must have idea". For use as an alternate or extra or whatever, but we NEED a shark texture for the dolphin model!

**Comment by Rabenweis** [comment]
I think the problem would be that it's literally a dolphin _model_. The snout and tail would be wrong and it just wouldn't look right.

I had the same thought about a raven texture for parrots, but since the beak would always look wrong, it wouldn't work.

**Comment by CreativeRealms** [comment]
If we get sharks they would end up being their own mob. Closed since it's not currently on the to-do list.
