### ISSUE TITLE
Survival Odds.

### ISSUE THREAD

**Issue by P0188** [Conquest-Reforged/ConquestReforged#265]
at first when i started minecraft with this mod i thought survival would be fairly straight forward until i discovered wooden tools to no be a thing anymore, at first i didn't think too much of it given that there had to be some other way to keep progression going so i searched around and discovered that wood tools  now in place with flint tools. not going to lie i thought that was a neat idea.

then i discovered a post about flint rarity after not having found much of it myself and came to the realization after clearing out half a fairly decent sized land mass and discovering 0 flint. 0. flint.

whats going on here? i feel like conquest tried so hard to be a creative masterpiece that it neglected what minecraft was - a survival game.

**Comment by DiggyNevs** [comment]
Make sure you have generated the world with the Conquest world type generator. Also dirt/grass types occasionally drop flint.

**Comment by CreativeRealms** [comment]
This issue will be fixed in 1.14.
