### ISSUE TITLE
Survival: Crafting recipe for "Brown Window Pane" produces 6 "Window Trapdoor"

### ISSUE THREAD

**Issue by ModernPromethea** [Conquest-Reforged/ConquestReforged#270]
Both manually and automatically (through the crafting book) attempting to create Brown Window Pane with 6 Windows results in 6 Window Trapdoor instead of 16 Brown Window Pane. This Window Trapdoor object will not open or close like a wooden trapdoor, nor with a button or lever like an iron trapdoor. According to the crafting book, the recipe is supposed to produce the object Brown Window Pane.

I am using only the mods recommended and installed by the launcher.

![2018-08-20_19 47 59](https://user-images.githubusercontent.com/42558445/44372778-9292de00-a4b3-11e8-8265-2d4cba5431d9.png)
![2018-08-20_19 47 05](https://user-images.githubusercontent.com/42558445/44372790-99b9ec00-a4b3-11e8-9495-5a85f2473548.png)

**Comment by CreativeRealms** [comment]
Recipes will be redone in 1.14.
