### ISSUE TITLE
Tree and forest biome generation

### ISSUE THREAD

**Issue by jrkulmer** [Conquest-Reforged/ConquestReforged#272]
Two issues in one:

1. The tree generation, although aesthetically quite pleasing, is not well suited to immersion or survival - chopping down trees and receiving fences is an immersion-breaker. Also, I have been trying to configure treecapitator to work with these trees - to no avail - there seems to be two issues preventing successful integration:
A - the treecapitator algorithm cannot often "find" the top of a "tree" - this is due to forest biomes generating in such a way that the leaf and wood content of a tree often overlaps with other trees.
B - The connection of pillars non-vertically, trapdoors and vertical slabs seems to not be recognised by the algorithm as being connected at all.

My suggestions would be:

- Only use logs and pillars (vertically) for tree generation. Other tiles would be immersion breaking in the context of survival. However, slabs could be incorporated into aesthetic design IF they were to transform into regular wood upon destruction. Programming this would be cumbersome though, I presume.
- Adjust the generation algorithm so that trees do not overlap. However this may be aesthetically displeasing, so with integration with treecapitator in mind, a suggestion might be to have the outermost layer of leaves on any tree be technically a different block so that this block can be left out of the leaf registration for a tree in treecapitator, and not affect the calculation of the top of the tree.

2. The biome (especially noticeable for forest biomes) boundaries are very very sudden, which is again, unrealistic. If there could be a transition between biomes this would be much more immersive. Another immersion breaker is the fact that only one type of tree is found in a given forest biome. My suggestion would be that, for example, a beech forest biome shouldn't contain 100% beech trees, but instead 60 - 75% beech trees, with others inbetween, as well as shrubs on the forest floor.

I hope that these suggestions can be taken on board, as this mod is the single most immersive minecraft mod I've ever come across (especially in terms of world decoration) and it would be excellent if it could be tweaked to be just a little more immersive!

**Comment by CreativeRealms** [comment]
Trees will be tweaked in 1.14.

**Comment by CreativeRealms** [comment]
World gen is being redone in 1.17.
