### ISSUE TITLE
Trapdoors are not pet friendly

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#273]
So i've made an arched doorway (with 2 arches and cobble trapdoors) and i was surprised my dogs didn't follow me through.

Apparently, mobs see the block as solid and do not even attempt to go through even tho the hole is perfectly large enough for their body to pass. It occurred for zombies as well...

![2018-09-17_21 29 17](https://user-images.githubusercontent.com/18398566/45659152-0fb86f80-bac1-11e8-82ec-729b1b9bfca3.png)

**Comment by CreativeRealms** [comment]
Vanilla bug
