### ISSUE TITLE
Conquest Reforged mod prevents multiplayer gui mod Reauth from working

### ISSUE THREAD

**Issue by mindcloud69** [Conquest-Reforged/ConquestReforged#278]
The server connect gui under multiplayer is preventing [Reauth](https://minecraft.curseforge.com/projects/reauth) GUI from working correctly. Works when CR mod is removed. Also works when you delete the com\conquestreforged\connect\ folder from the jar file. can we please get a fix or config to disable the servers added to CR mod.

MC 1.12.2
forge-1.12.2-14.23.4.2760
ConquestReforged-3.0.2-mc1.12.2.jar
reauth-3.6.0.jar

**Comment by HIPPOKLEIDES** [comment]
Can you show how the GUI is not working correctly?

**Comment by mindcloud69** [comment]
You literally can not use it to relogin. You click on the reauth buttons and it does nothing. But as soon as you remove the connect folder from the CR jar it works again.
