### ISSUE TITLE
Iron Railing recipe produces iron stairs

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#281]
The recipes for "Iron Railing" and "Iron stairs" both suggests 3 metal grates placed in a " / " shape but that always gives a set of iron stairs. Iron Railing is therefore impossible to get in Survival.

![2018-11-25_22 27 30](https://user-images.githubusercontent.com/18398566/48991556-54840680-f101-11e8-849b-2594466a0d17.png)

Please make sure "iron stairs" and "iron railing" have separate recipes. Also, using Iron Bars as components for crafting Iron Railing and Iron Straight Railing would seem more appropriate than the Metal Grate. Metal Grate works great for the Iron Stairs tho 👍

**Comment by CreativeRealms** [comment]
Recipes will be changed in 1.14.
