### ISSUE TITLE
The all-sided spruce log cannot be used in crafting recipes

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#282]
Spruce Sapplings do beautiful Spruce trees that yield all-bark Spruce Logs when cut down.

This all-bark Spruce Log (ID 4950/3) is not valid for many recipes involving the vanilla Spruce Log including:

- Trapdoors
- Horizontal slabs
- Vertical slabs
- Wall of Spruce wood (required for Wooden Stairs, a precious 45deg angled backside for roofs 👍 )
- etc...

This, in a Conquest generated Survival world, leaves only the few Cypress trees as the sole default Spruce-Log- yielding source of the vanilla Spruce log that works for the aforementioned recipes.

We should be able to switch all-bark logs to all-cut logs to default log variants at all times to avoid blocking recipes.

**Comment by CreativeRealms** [comment]
Recipes will be redone in 1.14.
