### ISSUE TITLE
Hewn Stone with Stone Brick CTM Connects to Wrong Blocks

### ISSUE THREAD

**Issue by Alex33212** [Conquest-Reforged/ConquestReforged#289]
While it looks excellent, the Hewn Stone with Stone Brick CTM appears to be bugged; it connects to many other types of blocks as if they are itself. Now, with Hewn Stone blocks, that works well, but it visually connects to stone bricks (which removes the nice trim), regular bricks, and what seems to be any block considered stone or stone-like, including tudor frame blocks and roof tiles.

**Comment by Alex33212** [comment]
the Stone Cobblestone block appears to have this issue as well

**Comment by CreativeRealms** [comment]
Working as intended as it's designed to be used as a corner block.
