### ISSUE TITLE
Sandstone and crash

### ISSUE THREAD

**Issue by azo1** [Conquest-Reforged/ConquestReforged#29]
Hey, I'm making a modpack based around conquest Reforged and have came across two issues.

1. For some unknown reason when I place 2 or more sandstone on top of each other the top one have the conquest texture but the blocks below don't. I'm guessing this is a connected textures issue? but I have no idea. 

![2018-03-31_01 22 26](https://user-images.githubusercontent.com/37944820/38157867-0c688d7a-3483-11e8-8ad2-5885509f4518.png)

2. When I open the game instantly crashes. Can someone go through the crash report please because I don't have enough knowledge of diagnosing crash reports. I'm going to post the crash report below. If you can put text behind a tab then sorry, I'm not used to github. 
 
Crash Fixed! it was bibliocraft crashing the game.

Thanks for the help!

**Comment by HIPPOKLEIDES** [comment]
1) It seems like you haven't enabled the Conquest Reforged resourcepack (a seperate download from the Conquest Reforged mod with all the necessary connected texture files). 
2) This is an issue with the Bibliocraft mod, which hasn't fully or properly implemented their custom model class (and therefore it conflicts with our block selection GUI)
