### ISSUE TITLE
Upside down Ionian & Corinthian Capital

### ISSUE THREAD

**Issue by IamDiversity** [Conquest-Reforged/ConquestReforged#290]
Hi,
I tried to rebuild this image from Hytale, it used Corinthian Capital but on the floor. the problem is that corinthian and ionian capitals can't be upside down. So can we get this bloc to be like stairs and can be upside down please ? And also if these two blocks can be designed to fit only 1 block and not over 1 block cause i get collisions glitch with other blocks.

![5c829bfb36e672001743d5a9_zone_1_interior](https://user-images.githubusercontent.com/32708474/54859309-f8766b00-4d0b-11e9-8702-fec2d8126a3f.jpg)
![2019-03-23_01 36 45](https://user-images.githubusercontent.com/32708474/54859372-a255f780-4d0c-11e9-8d3a-ac7d10e0da1a.png)

Thank you

**Comment by HIPPOKLEIDES** [comment]
can't see this happening as this would not occur in the classical orders
