### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by theishiopian** [Conquest-Reforged/ConquestReforged#292]
Your world generator seems to be having some issues. This pops up a lot in the log:

[20:25:10] [Server thread/WARN] [FML]: Conquest Reforged loaded a new chunk [59, 53] in dimension 0 (overworld) while populating chunk [58, 53], causing cascading worldgen lag.

I've actually had this issue with my own mod before, and the fix is easy. Just offset your generations by +8 in both x and z, this will prevent spillover into nearby chunks.

More info: https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/?ref=share&ref_source=embed&utm_content=body&utm_medium=post_embed&utm_name=c546f5acf95c46fdb115cdcc691c411a&utm_source=embedly&utm_term=5x0twz

**Comment by CreativeRealms** [comment]
World gen will be reworked in 1.14 and 1.12 will not receive future updates.
