### ISSUE TITLE
My minecraft suddenly crashing down. Help me 

### ISSUE THREAD

**Issue by mamaha09** [Conquest-Reforged/ConquestReforged#293]
[crash-2019-04-29_19.58.31-client.txt](https://github.com/Conquest-Reforged/ConquestReforged/files/3128505/crash-2019-04-29_19.58.31-client.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 4/29/19 7:38 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: -100
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:56)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1664119336 bytes (1587 MB) / 3523215360 bytes (3360 MB) up to 3690987520 bytes (3520 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3500M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2824 Optifine OptiFine_1.12.2_HD_U_E3 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                 | Source                                | Signature                                |
	|:------ |:--------------- |:----------------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2                  | minecraft.jar                         | None                                     |
	| LCHIJA | mcp             | 9.42                    | minecraft.jar                         | None                                     |
	| LCHIJA | FML             | 8.0.99.99               | forge-1.12.2-14.23.5.2824.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2824            | forge-1.12.2-14.23.5.2824.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore     | 7.7.4                   | minecraft.jar                         | None                                     |
	| LCHIJA | backpack        | 3.0.2                   | Backpacks-Mod-1.12.2.jar              | None                                     |
	| LCHIJA | xaerobetterpvp  | 1.16.5                  | BetterPvP_1.16.5_Forge_1.12.jar       | None                                     |
	| LCHIJA | conquest        | 3.0.2                   | ConquestReforged-3.0.2-mc1.12.2.jar   | None                                     |
	| LCHIJA | blockpalette    | 1.5.0                   | ConquestReforged-3.0.2-mc1.12.2.jar   | None                                     |
	| LCHIJA | connect         | 1.0.3-mc1.12.2-SNAPSHOT | ConquestReforged-3.0.2-mc1.12.2.jar   | None                                     |
	| LCHIJA | foamfix         | 0.10.5-1.12.2           | foamfix-0.10.5-1.12.2.jar             | None                                     |
	| LCHIJA | forgelin        | 1.8.2                   | Forgelin-1.8.2.jar                    | None                                     |
	| LCHIJA | waila           | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar           | None                                     |
	| LCHIJA | inventorytweaks | 1.64+dev.146.2180b27    | InventoryTweaks-1.64+dev.146.jar      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jei             | 4.13.1.225              | jei_1.12.2-4.13.1.225.jar             | None                                     |
	| LCHIJA | shadowmc        | 3.8.0                   | ShadowMC-1.12-3.8.0.jar               | None                                     |
	| LCHIJA | leveluphp       | 1.12.2-1.4.0            | leveluphp-1.12.2-1.4.0.jar            | None                                     |
	| LCHIJA | minersadvantage | 1.3.19.242              | MinersAdvantage-1.12.2-1.3.19.243.jar | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6286' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2824
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 24.20.100.6286, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 24.20.100.6286
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by dags-** [comment]
Answered on discord
