### ISSUE TITLE
Meteorites

### ISSUE THREAD

**Issue by Justusius** [Conquest-Reforged/ConquestReforged#294]
Is it an issue that these meteorites are falling everywhere and every 30 seconds?

**Comment by GuusLieben** [comment]
There are no meteorites in the Conquest Reforged mod, nor in the texturepack. Are you using additional mods or Shaders?

**Comment by Justusius** [comment]
It is in the BodTheConquerercore mod

Guus Lieben <notifications@github.com> schrieb am Do., 11. Juli 2019, 19:05:
