### ISSUE TITLE
Incompatibility with Unique Crops mod

### ISSUE THREAD

**Issue by Wurgrim** [Conquest-Reforged/ConquestReforged#295]
I have been trying a few mods with the Reforged mod and when I tried Unique Crops on, the game wouldn't start anymore.
 Here is the crash log : https://pastebin.com/NBQR986g .
 Although the reforge mod shouldn't affect this mod at all since it only ads just a few new crops and items.
 Any ideas what can cause the crash ?

**Comment by GuusLieben** [comment]
It seems your version of Forge and the Unique Crops mod don't match, the mod is newer than the Forge version provides. Your best bet is either upgrading Forge, or using an older version of the mod. Also make sure you're using a 1.12.2 version of Unique Crops, as your current version is for 1.12.0

**Comment by HIPPOKLEIDES** [comment]
1.12 CR won't be updated, and crash log link is dead, so closing
