### ISSUE TITLE
Modded Ore Quantity

### ISSUE THREAD

**Issue by Ghiojo** [Conquest-Reforged/ConquestReforged#297]
I noticed when Looking around to use conquest reforged that the conquest world doesn't generate very many ores that aren't vanilla/part of conquest when done, got an Xray to double-check such. Don't know if there is a feature like that already, otherwise, it'd be good to suggest a way for at least tweaking or being able to up the ammount of modded ores that generate in the world.

If there is a way to tweak the generation to allow this, what's the way to do so?

**Comment by CreativeRealms** [comment]
At the moment there is no way to tweak ore gen. There should be an option in 1.14.
