### ISSUE TITLE
ConquestOfTheSun Shader buggy (FIXED) + No Connected Texture (won't follow the Setting)

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#30]
As seen below, the Conquest of the Sun shader (copied from my Conquest 1.10.2 instance) gives wierd results in the new version. There's a black circle that covers a third of the screen... Turning Shaders OFF fixes it but i like my shaders.

Also the Connected texture doesnt work for me. I tried Fast or Fancy setting and nothing works. Regardless of any Shaders i use.

![2018-03-31_12 31 55](https://user-images.githubusercontent.com/18398566/38165360-0e0968ea-34e0-11e8-904a-5a6213d419cb.png)

My setup is :
- Acer Laptop Nitro AN515-51 (8GB RAM, Intel i5-7300, SSD)
- Windows 10 x64 (up-to-date)
- Nvidia GeForce GTX 1050
- Minecraft Default Install (what i had before i installed a new CR 1.10.2 instance in another folder)
- Forge 1.12.2 
- OptiFine 1.12.2 D1 
- Conquest Reforged 3.0.0 1.12.2 mod from Patreon (Feb 18's post) 
- Conquest dev Resource Pack from Patreon (Feb 6' post)

**Comment by boivsamuel** [comment]
Well turns out looking at my Shaders screen i noticed it was running on the integrated Intel GPU 👎 

My stupid NVidia control panel reverted my choice to "Always use Nvidia Advanced processing"... and java execution got set back to using the integrated graphics. Fixed that and the Shaders now work fine:

![2018-03-31_12 59 51](https://user-images.githubusercontent.com/18398566/38165563-796e873e-34e3-11e8-8952-9c3ed79ba4e0.png)

Still having issues with Connected Textures tho.... 😭

**Comment by HIPPOKLEIDES** [comment]
CTM most likely broken due to an improper conversion (see my other replies).

**Comment by boivsamuel** [comment]
I fixed the CTM by enabling Better grass (go figure why that option had any effect on other blocks than grass)
