### ISSUE TITLE
Request for blonde/honey colored woods

### ISSUE THREAD

**Issue by Sjaelkie** [Conquest-Reforged/ConquestReforged#301]
E.g. such as IRL pine, fir, birch. Sort of like stripped birch and stripped oak in MC vanilla. Any lighter /warmer wood colors.

(first time here, so not too sure how I can label this as a suggestion! thanks for suggesting on CR discord that I post here)

**Comment by CreativeRealms** [comment]
Lots of new wood types in the next update. You'll probably find what you need.
