### ISSUE TITLE
Light spruce needles drop willow saplings.

### ISSUE THREAD

**Issue by AkGamerRo** [Conquest-Reforged/ConquestReforged#309]
Why do light **SPRUCE** needles(leaves) drop **WILLOW** saplings when broken by hand or axe, instead of spruce or pine(the tree I planted and bone mealed)? 

Also I have yet to find a pine planted by me grow with leaves that also drop pine saplings. So far most of them droped willow, spruce and ocasionaly dark oak saplings. I love the pine planks but I hate to travel MILES to get pine saplings because mine grew with leaves that drop willow instead.

I'm using your launcher on the 1.12 (advanced) version.

**Comment by CreativeRealms** [comment]
We are fixing these issues in the 1.14.4 version as survival in 1.12.2 was only a basic implementation.

**Comment by CreativeRealms** [comment]
Will be overhauled in 1.15.2.
