### ISSUE TITLE
Light Gravel + Lothlorien Dirt behave like moving foliage

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#31]
Somehow, in CR 1.12.2, Light Gravel moves like foliage (weeds & leaves) blocks. Pretty sure that aint normal. My world is a conversion from CR 1.10.2

![2018-03-31_18 11 52](https://user-images.githubusercontent.com/18398566/38168010-177dce78-350f-11e8-9b45-663f8f9404a8.png)
![2018-03-31_18 11 55](https://user-images.githubusercontent.com/18398566/38168011-17b7b2be-350f-11e8-9111-8ae536dd820c.png)

**Comment by boivsamuel** [comment]
Seems to affect **conquest:ground_full_2** **conquest:ground_full_3**.

conquest:ground_full_1 looks okay...

**Comment by HIPPOKLEIDES** [comment]
There is no converter out for Conquest Reforged 1.10.2 - 1.12.2... so I'm not sure what you have done to convert it. In any case the two are the same with respect to their code, so something is going wrong with your shaders or your conversion.

**Comment by boivsamuel** [comment]
@HIPPOKLEIDES Well i opened my 1.10.2 world in a 1.12.2 install and besides a warning the first time around it's been running rather smooth. There's some blocks that changed ID (either they no longer have name and/or textures) and i have to replace them with the new instance of the same block but nothing that cannot be done manually over a few hours. I'm really surprised to hear it shouldnt be converted haha

**Comment by boivsamuel** [comment]
Still occurs in a 1.12.2 brand new world...
