### ISSUE TITLE
Some suggestions for Creative

### ISSUE THREAD

**Issue by Choriphus** [Conquest-Reforged/ConquestReforged#312]
**Weapon rack varieties** _[Accessible by pop-menu]_ Medieval Variants, Dwarven, Elven, Orc, Steampunk. 
_Application - Being able to better furnish style specific builds, without contrasting subject matter._

**Colored lighting** [Accessible by Invisible Lighting Blocks pop-up menu(Item icon representing color)]
[Example](https://www.curseforge.com/minecraft/mc-mods/colored-lights) 
_Application - Being able to better represent atmosphere, especially fantasy atmosphere styles using non-standard lighting sources._

**Colored Light sources** [Giving each light source i.e. Torch, Lit Chandelier, Hanging Brazier, etc, color variants]
_Application - Being able to better represent fantasy atmosphere._

**Comment by CreativeRealms** [comment]
Colored lights might be difficult especially with recent changes to rendering in 1.15 and I don't know if Optifine is able to use them at all (the mod you linked does not work with Optifine). That doesn't mean it will never happen but there would be some barriers that may have to be overcome before something like that is implemented.
