### ISSUE TITLE
Normal? Toggling grape/cabbage crates changes their texture

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#32]
Flat Grapes Crate texture gives some weird brown box
Angled Cabbage Crate give some light grey box.

I'm not sure if they are intended attempts at shattered wood crate or iron cage or if the texture is buggy.

![2018-03-31_21 08 25](https://user-images.githubusercontent.com/18398566/38168885-f8ea4072-3527-11e8-83b9-67a5060d71db.png)

**Comment by HIPPOKLEIDES** [comment]
No, this is not normal. This is most likely due to opening an improperly converted 1.10.2 map in 1.12.2

**Comment by boivsamuel** [comment]
Not to be annoying but i've tried in a new 1.12.2 world i just created and same thing... You should reopen and have a look for real.

![2018-03-31_21 28 30](https://user-images.githubusercontent.com/18398566/38168965-95e4fe9c-352a-11e8-8dd6-234e23c53362.png)
