### ISSUE TITLE
Cant match block colors with biome colors when Chiseled

### ISSUE THREAD

**Issue by ricey125** [Conquest-Reforged/ConquestReforged#322]
Hello, I am using conquest reforged mod along with C&B. Ive noticed that diorite and stone do not retain their swampland color when chiseled while grass and leaves do. I was wondering if there is a simple fix for this?
MC Version: 1.12.2
C&B Version: 14.33
Do You have Optifine: Yes
Conquest Reforged: 3.0.2-mc1.12.2

**Comment by dags-** [comment]
Don't think there's anything we can do on our party sorry. The biome coloring on blocks like stone is an Optifine feature. Chisel would probably have to add support for that to render the blocks as expected.

If you just want the blocks to match up and arew willing to sacrifice biome-specific textures/coloring then I think there's an option in video settings to turn that part of Optifine off

**Comment by ricey125** [comment]
They told me that its not a problem on their end, I was just wanting to keep that biome specific color when I chisel the block instead of it reverting back to its normal state. Is it possible at all?

**Comment by dags-** [comment]
They told you they were not willig to make any more code changes to 1.12 - presumably they've moved onto 1.14 and above.
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/491

I'm sorry but it's out of CR's hands/scope to support. We don't have control over Optifine to be able to add support for C&B to that. And we don't have control over C&B to be able to add support for Optifine's features.

You'd have this problem with any resourcepack using that Optifine feature with C&B

**Comment by xemnes** [comment]
thought i would put in some input on this

when you chisel a block, the block id changes which is why the biome colour is different. its not as simple as adding that block id for the chiseled block to the list of tinted blocks because then all blocks that are chiseled will also be tinted that colour and you may not want that.

the only solution i found was to pre-tint the textures you want to be that colour, then use ctm to apply it to each biome.

**Comment by dags-** [comment]
I think we'd need Optifine to support biome colouring by matching on texture rather than block then.

I know there's something like `matchTiles` for this with CTM. The docs for biome colours only mentions matching on block types - might be worth putting in a feature request with Optifine?

**Comment by xemnes** [comment]
i kinda asked for this feature already due to retinting the grass blocks in CR with optifine causing the entire block to tint and not just the grass. he said he might look into it, this was a looong time ago now.

**Comment by dags-** [comment]
I'll mention it to monster, he probably pulls a bit more weight than myself in those circles.
Might also have his own input and knowledge of any caveats with this approach.

**Comment by xemnes** [comment]
awesome, will love to hear what the outcome of this is as i would benefit from it also.

**Comment by ricey125** [comment]
Thanks guys for your input, you were really helpful. For now Im going to go with the retexture of diorite and stone, but how would I go about doing this with the launcher version of the mod?

**Comment by dags-** [comment]
If you right-click the modpack in the launcher's modpack-list there should be an option to 'view game folder' or something. From there you should be able to find the mods folder with the CR jar in, or the resourcepacks folder with the CR resourcepack in it

**Comment by xemnes** [comment]
id do it from the resource pack, in the minecraft/mcpatcher/ctm folder
then from there, you place the modified textures you want to use, create a new properties file with it (can be named anything, like birchbiome.properties)

in that file, for biome specific, it would be:

matchTiles=domain:FilenameOfTextureYouWantToReplace
tiles=FilenameOfNewTexture (if in same folder as properties file, no need for domain)
method=random/fixed (either works)
biomes=list of biomes

capitalization is important

so for example, i have a texture named stonejungle.png with a properties file named stonejungle.properties and i want to replace assets/minecraft/textures/blocks/stone.png

```
matchTiles=minecraft:stone
tiles=stonejungle
method=fixed
biomes=Jungle JungleHills JungleEdge JungleMountains JungleEdgeMountains
```

another example but for a conquest mod texture, i have a texture named calcitejungle.png with a properties file named stonejungle.properties and i want to replace assets/conquest/textures/blocks/stone_calcite.png

```
matchTiles=conquest:stone_calcite
tiles=calcitejungle
method=fixed
biomes=Jungle JungleHills JungleEdge JungleMountains JungleEdgeMountains
```

(note that there may be more jungle biomes that i didnt list there)
its pretty much that simple, obviously you would need to create a new texture for every biome tint and then create a properties file for each for their corresponding biomes.

**Comment by ricey125** [comment]
Is there a way to take the texture of diorite when it is in the swampland and just duplicated it, then replace that with the regular texture and color of diorite? I can't seem to find swampland diorite texture in the resource pack.

**Comment by ricey125** [comment]
If not Ill just make a new texture and follow what you laid out for me.

**Comment by xemnes** [comment]
the diorite texture is inside the conquest reforged mod jar rather than the resource pack, it is stone_diorite.png

**Comment by ricey125** [comment]
So I have to open the .jar to get that texture and then transfer it over to the resource pack as diorite?

**Comment by xemnes** [comment]
yes.

**Comment by ricey125** [comment]
Well damn, because the .jar won't allow me to launch it.

**Comment by xemnes** [comment]
open it in a program like 7zip

**Comment by ricey125** [comment]
Its says it "cant launch .jar"

**Comment by xemnes** [comment]
![image](https://user-images.githubusercontent.com/603338/72850639-7c3d1300-3ca1-11ea-84a6-7ea3b7ddcb24.png)

**Comment by ricey125** [comment]
I have a mac, and use archive utility. It creates a .cpgz file that doesnt do anything.

**Comment by xemnes** [comment]
hmmm
try bandizip, you need to be able to open it as an archive.

**Comment by xemnes** [comment]
if needed, add me on discord Xemnes#2789

**Comment by ricey125** [comment]
Ill do that

**Comment by ricey125** [comment]
Thank you guys for your help. Great mod and great serivce 10/10!
