### ISSUE TITLE
Carved Rune and Carved Rune (Connected) look the same (not connected)

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#33]
After i managed to fix my CTM issue from a few hours ago, i took a look around my existing map and found that the Carved Runes (Connected) was no different that the not connected version. Pretty much all other connected textures do work fine so maybe this one has been overlooked.

i also double-checked in a newly created CR 1.12.2 world and the problem still occurs (so not a conversion issue @HIPPOKLEIDES). Thanks!

![2018-03-31_21 28 03](https://user-images.githubusercontent.com/18398566/38168997-92087082-352b-11e8-8b58-b1491287c00d.png)
![2018-03-31_21 21 31](https://user-images.githubusercontent.com/18398566/38168999-99ee87dc-352b-11e8-980b-0be53019606e.png)

**Comment by HIPPOKLEIDES** [comment]
Should be fixed, thanks for reporting these things :)
