### ISSUE TITLE
Roman Brick + Stucco

### ISSUE THREAD

**Issue by Dude7ox** [Conquest-Reforged/ConquestReforged#330]
Roman brick with peach stucco actually is with white stucco. (stucco in the middle) White on the left, peach on the right
![2020-02-07_15 26 40](https://user-images.githubusercontent.com/44357403/74022433-56ad4a80-49bf-11ea-8ae7-89f461914bff.png)

**Comment by CreativeRealms** [comment]
Fixed in 1.15.2.
