### ISSUE TITLE
Suggestion - New block

### ISSUE THREAD

**Issue by KEFarris** [Conquest-Reforged/ConquestReforged#336]
A "null" block, basically, a bock the acts like a solid, but is fully translucent.   This allows things that normally react to blocks around it to be placed next to it and change state based on this block.

**Comment by Mokumer** [comment]
I think this isnt needed because 1.14 has the debug stick KEFarris

**Comment by CreativeRealms** [comment]
> I think this isnt needed because 1.14 has the debug stick KEFarris

Correct and we will have a blockstate picker GUI
