### ISSUE TITLE
Possible broken recipe? Duplicate "Marble" entries - the one generated doesn't match recipe.

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#34]
So i'm in a Mediterranean biome generated in a new CR 1.12.2 world. I mined some regular Marble to make a nice Mediterranean home. However, from the recipe book, to make Smooth White Marble (and the rest of Marble cool blocks) i require 4 Marble + 1 Chisel (which i have in _names_ but not in _block id_).

What i mined is Marble (**conquest:stone_full_hard4**) but what the recipe expects is Marble (**conquest:stone_full_8**). Weird uh? Can the marble exist on 2 IDs and sadly this biome doesnt generate what is needed to make usable blocks?

![image](https://user-images.githubusercontent.com/18398566/38283073-e3fc8768-3781-11e8-8c3e-6a8e4befc693.png)

**Comment by boivsamuel** [comment]
Also notice the resource pack doesnt have textures for the non-naturally-generated-marble-that-i-cant-get... Green cubes!

Using the resource pack from CR 1.10.2 cuz the dev version from Patreon doesnt work properly (see my previous bugs)

**Comment by HIPPOKLEIDES** [comment]
Thought I fixed this in the release I just put out today, but looks like I missed it. It's fixed now at any rate. Thanks again for reporting these

**Comment by boivsamuel** [comment]
uhhmmmmm @HIPPOKLEIDES you might wanna recheck this fix cuz now there is no way to craft Smooth White Marble at all.... meaning all marble products are unattainable.
