### ISSUE TITLE
Filled railings?

### ISSUE THREAD

**Issue by Mokumer** [Conquest-Reforged/ConquestReforged#343]
Maybe it's pretty far fetched, but I think it would be a good idea to get some filled railings (the diagonal ones, not the straight ones) which could allow us to add a bit more shape to our roofs and constructions, basically functioning as a "half trapdoor".
The screenshot I added gives an idea of how I see it being used.
![image](https://user-images.githubusercontent.com/58232628/76611635-26574f80-651b-11ea-986a-1c218cecdecd.png)

**Comment by HIPPOKLEIDES** [comment]
We're added a "vertical corner slab" (like half a stair) for something like this. We won't be adding smooth triangular variants for this, and if we were to do anything like this, it'd probably come in the form of diagonal roofs.
