### ISSUE TITLE
More shapes and colored lighting options

### ISSUE THREAD

**Issue by Spejs** [Conquest-Reforged/ConquestReforged#344]
Would be very nice to have. For example, more color variants for paper lantern, candle that is redstone torch (only with good light level), maybe even glowstone or end rods. Different tinted bottles with fireflies in them. Glowing shards of crystal blocks. Also would be really nice to have something similar to nitor from thaumcraft mod.

**Comment by Spejs** [comment]
Also related to lighting options, would like to have at least one lighting block, maybe glowstone, that has shape variations like walls, stairs, slabs, etc. If you decide to add this, please don't forget newel cap shape.

**Comment by CreativeRealms** [comment]
Denied
