### ISSUE TITLE
"item.lime.name" in Clean White Plaster recipe missing its name and texture

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#35]
I wanted to make White Stucco, which is done with Clean White Plaster. And Clean White Plaster is made with something without a name or a texture apparently.... I guess it is something related to limestone but i cannot be sure. Both the name and textures are missing

Using the 1.10.2 or the conquest_reforged_dev (Feb 6th) from Patreon give out the same result.

![2018-04-04_15 47 19](https://user-images.githubusercontent.com/18398566/38330986-0979f2de-3820-11e8-998e-d6ef55db96df.png)

**Comment by HIPPOKLEIDES** [comment]
The lime item should be gone from recipes and replaced with bonemeal now.

**Comment by boivsamuel** [comment]
works like a charm now
