### ISSUE TITLE
Slab on top of beam is invisible when viewed from underneath

### ISSUE THREAD

**Issue by kapunga** [Conquest-Reforged/ConquestReforged#351]
I placed a slab on top of a Pine Wood Beam Horizontal and when viewed from underneath, the slab is invisible. I tried this with several different slabs and they all were invisible. I did not try a different beam.
![2020-05-16_10 14 09](https://user-images.githubusercontent.com/2872290/82122495-113cae00-9762-11ea-84f8-15b4fbe2aa82.png)
![2020-05-16_10 14 18](https://user-images.githubusercontent.com/2872290/82122496-113cae00-9762-11ea-92f1-c6b2c06291e2.png)
![2020-05-16_10 14 25](https://user-images.githubusercontent.com/2872290/82122497-11d54480-9762-11ea-95ec-c8fa35143d05.png)

**Comment by HIPPOKLEIDES** [comment]
fixed in the latest alpha
