### ISSUE TITLE
Switch the texture rotation on Bundled logpile with the regular logpile

### ISSUE THREAD

**Issue by Silthulhu** [Conquest-Reforged/ConquestReforged#352]
CR 4.0.0-v0.5
OPT HD_U_G1_pre23
FRG 31.2.9

Nobody uses the bundled logpile for stacked firewood / logpiles, and the bundled version makes more sense for using as walls, so we propose you switch the rotation on the block variants to be the opposite way around (bundled version are all vertical, nonbundled version are all horizontal)

Basically the opposite of what they are currently in these following screenshots.
![2020-06-11_15 35 01](https://user-images.githubusercontent.com/57784733/84358793-c5bfd780-ac1b-11ea-9a81-0b9c07b07a9e.png)

![2020-06-11_15 33 44](https://user-images.githubusercontent.com/57784733/84358864-e25c0f80-ac1b-11ea-8bc8-2c802e38779e.png)

Also add that angled log pile model Monster started that's more like the Medifault one / the one there was in 1.10.2 CR, please and thank you ^_^

**Comment by CreativeRealms** [comment]
Semi-implemented in 1.15.2.
