### ISSUE TITLE
Texture Issues - "Chains on the ground" & Beam Walls

### ISSUE THREAD

**Issue by ByteSizeDev** [Conquest-Reforged/ConquestReforged#355]
| File | Version |
| ------------- |:-------------:|
| Conquest Reforged      | 1.15.2-4.0.0-v0.5 |
| Optifine      | 1.15.2_HD_U_G1_pre30 |
| Resource Pack | ALPHA-31|

Hi,
Not sure if these are known issues but I encountered them today while building around.

1. Chains on the ground not retexturing properly when trying to make ascending line. Debug stick does not fix form. I can do this with the rope equivalent and there are no issues.

![chain_on_the_ground](https://user-images.githubusercontent.com/67930601/86655755-f72a8980-bfb4-11ea-939a-1f3b6af34870.png)

<hr>

2. It seems that every kind of "beam-wood" wall has an invisible center segment when connected in a line of 3+
You can set the center section to a pillar texture with debug stick but I would like to be able to have long thin sections as with stone wall variants. I include a section of cobble wall as an example of how it should look.

![beam_walls](https://user-images.githubusercontent.com/67930601/86656166-44a6f680-bfb5-11ea-9b20-3141c531a9a5.png)

If there is anything to be done about these, much appreciated.

Looking forward to continuing to build with 1.15 as it gets fleshed out.
Cheers!

**Comment by HIPPOKLEIDES** [comment]
was recently fixed
