### ISSUE TITLE
No Better Foliage in stand alone mod?

### ISSUE THREAD

**Issue by BubbySkittles** [Conquest-Reforged/ConquestReforged#358]
I've downloaded the separate conquest reforged mod and conquest reforged resourcepack instead of the launcher, but in game, there is no better foliage. Leaves are still square blocks, despite the fact I've seen the better foliage watching others' gameplay. Please help!

**Comment by CreativeRealms** [comment]
You need to put this in your mods folder https://www.curseforge.com/minecraft/mc-mods/better-foliage
