### ISSUE TITLE
Tin Ore Block drops Tin Ore Block which is not smeltable.

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#36]
Just found a Tin Ore deposit... Mining it dropped Tin Ore blocks and these wont melt in a furnace or have any purpose...

I believe Tin Ore Blocks should be smeltable?

**Comment by HIPPOKLEIDES** [comment]
you need to combine tin ore and bronze ore and smelt the item you get.
