### ISSUE TITLE
(Suggestion)

### ISSUE THREAD

**Issue by KatskoDarwin** [Conquest-Reforged/ConquestReforged#360]
Hey, as a ship lover, I always wanted to improve the current cannon design, could we get a cannon block please, or some small wheels that would look like the ones all the cannons have. Also diagonal rope ladders would be amazing for the rigging of a ship, instead of using the regular jungle fence gate/ jungle fence. That's all thank you for your time :)

**Comment by CreativeRealms** [comment]
Duplicate of https://github.com/Conquest-Reforged/Indev/issues/294
