### ISSUE TITLE
My Launcher isn't working and I Don't know why.

### ISSUE THREAD

**Issue by summerrains1** [Conquest-Reforged/ConquestReforged#361]
I've downloaded the Launcher 4 times now and it only worked once for some reason. when it doesn't work an error occurs and it says ''1 file(s) could not be downloaded''. I've tried restarting my laptop and clearing space but nothing fixes it. I've tried looking up what the error means but it only comes up with GTA stuff.

**Comment by CreativeRealms** [comment]
If it’s still in your downloads folder move the launcher to a new folder somewhere else. It likely doesn’t have write permissions which prevents it from working.

**Comment by summerrains1** [comment]
Thank you, it's working perfectly now!
