### ISSUE TITLE
Bags ... (Minecraft v. 1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [Conquest-Reforged/ConquestReforged#362]
Hey.
I installed your mod and saw some bugs with textures:
- by the torch in my hand (squares);
- many, many, many pigeons!
I attach a screenshot.
![2020-09-30_14 28 14](https://user-images.githubusercontent.com/46864165/94679857-77008f80-0329-11eb-8231-9309abf57532.png)

**Comment by CreativeRealms** [comment]
You need the resourcepack https://www.curseforge.com/minecraft/texture-packs/conquest-reforged-resource-pack and Optifine https://www.optifine.net/downloads installed.
