### ISSUE TITLE
Takes forever to load (the main screen)

### ISSUE THREAD

**Issue by KBOC359** [Conquest-Reforged/ConquestReforged#364]
i am using version 1.16.4 with optifine, whenever i enable the texture pack it just keeps fluctuating my ram, it goes from 1 gigabyte to 6 gigabytes which is the maximum allocated, but nothing happens, it just freezes my entire computer and never loads, just eats ram.

![javaw_HEXEexJtu5](https://user-images.githubusercontent.com/31526906/101137443-82b54e80-3617-11eb-8cc2-7475cf94053a.png)

**Comment by CreativeRealms** [comment]
This is the github for the Conquest Reforged mod not the Conquest resourcepack. Regardless, 1.16.4 has terrible performance issues and loading the vanilla pack can take 5min (more or less) based on your computer specs. You'll just have to wait it out.
