### ISSUE TITLE
Spruce sappling in Mediterranean Biome grows into Birch tree

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#37]
I had a spruce sappling obtained from one naturally generated cypress tree. Once planted it turned into a birch tree (Birch Log).

![2018-04-04_17 13 53](https://user-images.githubusercontent.com/18398566/38335351-01ce0e24-382c-11e8-9071-fa6d16b0cb62.png)

![2018-04-04_17 14 37](https://user-images.githubusercontent.com/18398566/38335352-0567edfc-382c-11e8-87ba-28c23b062642.png)

**Comment by HIPPOKLEIDES** [comment]
This is working as intended. I'm afraid we don't have enough resources to make saplings for all the trees we have generating, so the saplings are really there to provide an avenue for you to get the different leaves and woods. In any case it might be something for the future.

**Comment by boivsamuel** [comment]
So it's somehow normal that planting a sapling gives a different type of wood with a different type of leaves that drops another type of sapling?

Been playing a lot today and i was just confused...
