### ISSUE TITLE
Z-fighting on Beams (and other blocks)

### ISSUE THREAD

**Issue by TheMagicalChicken** [Conquest-Reforged/ConquestReforged#371]
**Is your feature request related to a problem? Please describe.**
While it isn't game breaking the Z-fighting seen on when placing many blocks that extend their models outside their 1 block size is annoying and really damages immersion, for me at least. The most pronounced example for me is with beams and anything next to them including other beams.

**Describe the solution you'd like**
Please slightly change (preferably reduce) the dimensions of these blocks using inflation to a small enough degree that is not noticeable but will prevent aforementioned texture clipping.

This fix is notably already applied to regular columns and arch blocks that have similar overlap with adjacent blocks - although the error still persists on the corner of these blocks and anywhere with Ionian columns (see below image).

**Describe alternatives you've considered**
Not really applicable.
I will say that the columns are less important since they would rarely be placed adjacent to another block with an exposed top/bottom, but the beam thing is a problem I have come across a lot in my own builds.

**Additional context**
![image](https://user-images.githubusercontent.com/47616279/118683204-17dc8600-b7f9-11eb-87bc-f38f70146362.png)
Examples of Z-fighting
![image](https://user-images.githubusercontent.com/47616279/118684057-cd0f3e00-b7f9-11eb-9180-51959cbdc1bd.png)
Beams Z-fighting (I have changed the material to make it more visible for a still image but it is also very noticeable even when they are the same material).

![image](https://user-images.githubusercontent.com/47616279/118684404-15c6f700-b7fa-11eb-8be1-6cbb3e11843e.png)
Wooden staircases also Z-fight with itself though it isn't that bad since the areas that do are rarely seen.

**Comment by CreativeRealms** [comment]
Closed 1.12.2 is no longer being updated.
