### ISSUE TITLE
Bug Report - Flower Pots have Apple Texture when Placed in Resource Pack

### ISSUE THREAD

**Issue by MrSwagOnWheels** [Conquest-Reforged/ConquestReforged#372]
**Mod Version & Build Number**    
The resource pack Conquest_1.16.zip

**Forge Version**    
N/A

**Describe the bug**    
Flower pots have the texture of an apple or tomato when placed. While in hand and in inventory, they're ceramic.

**Crash Log**    
N/A

**Screenshots/Video**    
![conquest bug](https://user-images.githubusercontent.com/14795683/120907877-ebaf6a80-c62a-11eb-96c0-c83987ae8aa1.png)

**System Information (optional)**    
N/A

**Additional context**    
N/A

**Comment by CreativeRealms** [comment]
Not a mod bug. Ask in the vanilla resourcepack Discord instead https://discord.gg/ehTcUDk
