### ISSUE TITLE
pillars = acacia log

### ISSUE THREAD

**Issue by queenlumia** [Conquest-Reforged/ConquestReforged#373]
**Mod Version & Build Number**    
ConquestReforged-mc1.16.5-5.0.0

**Forge Version**    
forge-1.16.5-36.0.0-installer

**Describe the bug**    
The pillars looks like acacia logs

**Crash Log**    
If your game crashed please upload a crash log (pastebin.com being the preferred method).

**Screenshots/Video**    

**System Information (optional)**    
Total RAM:  16  
Allocated RAM:    7
CPU:    
GPU:

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
Has been fixed by the latest alpha updates
