### ISSUE TITLE
Baroque Oak door Backwards Texture

### ISSUE THREAD

**Issue by MystycLegend** [Conquest-Reforged/ConquestReforged#374]
**Mod Version & Build Number**
ConquestReforged-mc1.15.2

**Forge Version**
forge-1.16.5-31.2.50

**Describe the bug**    
Issue with the resource pack. 
The Baroque Oak door (baroque_oak_door) texture is backwards when the right-hand door is closed and when the left-hand door is open. 
This is not an issue with the other door types. 

**Screenshots/Video**    
Screenshots attached: https://imgur.com/a/2btjDKB

**Comment by HIPPOKLEIDES** [comment]
Fixed for next release. Thanks for the report
