### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by GoodLordHelpMe** [Conquest-Reforged/ConquestReforged#375]
****THIS IS AN OPTIFINE COMPATIBILITY ERROR****
(Which should mean it is in the other mod compatibility area but I created this before I realised it was optifine related.)
It is to do with this optifine setting.
![2021-10-14_07 03 31](https://user-images.githubusercontent.com/92475877/137205470-264a15f4-4a66-4199-95fc-023d35e3566f.png)

**Mod Version & Build Number & Forge Version**

![image](https://user-images.githubusercontent.com/92475877/137201755-04963dec-fa4b-4863-9022-640a2be0d84e.png)

**Describe the bug**    
Now firstly I think this has something to do with Anisotropic filtering or whatever it is called, the optifine setting for restoring detail to mip maps. The blocks are unchanged and don't seem to be effected at it, just the texture that is on the blocks is messed up. It also only happens when you have a line of blocks and then another line intersecting. If there is not more blocks, above or below or a line going through then the textures are fine.
**Crash Log**    
Game did **NOT** crash.

**Screenshots/Video**    
I did open F3 but there didn't seem to be anything to do with blockstates about it, sent a screenshot just in case of F3 though.
![2021-10-14_06 39 52](https://user-images.githubusercontent.com/92475877/137202141-f00fbbbb-b79b-46a0-bf64-06378a0c8f0e.png)
![2021-10-14_06 25 07](https://user-images.githubusercontent.com/92475877/137201179-7e77ed20-515d-4b7e-87ac-58dcd84bf8ec.png)

**System Information (optional)**

This is a laptop and it is a pretty average one, not good nor bad.
Total RAM:    8GB
Allocated RAM:    6GB (But only 4 seems to ever get used by MC)
CPU:    Ryzen 5 3500U
GPU:    Integrated Graphics Card

**Additional context**    
I believe it is related to optifine, I think it is purely to do with textures, as far as I can tell there is no blockstate.

**Comment by HIPPOKLEIDES** [comment]
Avoided by turning off anistropic filtering and antialiasing, which are broken Optifine features.
