### ISSUE TITLE
Texture Bug

### ISSUE THREAD

**Issue by GoodLordHelpMe** [Conquest-Reforged/ConquestReforged#376]
Most Recent Version in the launcher.
![image](https://user-images.githubusercontent.com/92475877/137677237-14151ce3-3ded-4302-bea3-63656f3989e9.png)

**Bug Description**    
A bug where the texture of 'Fancy Black Socle' is sometimes one thing and other times another thing. This effects the block when placed horizontally in a line and in connected mode as well as when placed alone.

**Screenshots/Video**    
![2021-10-18_17 06 15](https://user-images.githubusercontent.com/92475877/137677547-41f65ae8-9db9-4a28-87fe-82301979066e.png)

**Additional context**    
Mods in use are all the ones selectable in the launcher and optifine. It is not a problem with Anti Aliasing or Anisotropic Filtering. It also isn't a smooth lighting problem because apparently that too can cause problems.

**Comment by HIPPOKLEIDES** [comment]
Changed for next release. Thank you for the feedback
