### ISSUE TITLE
1.16.5 Beta - Mismatched Textures for Mod-added Rug/Carpet Cover Blocks

### ISSUE THREAD

**Issue by Jigglebrugal** [Conquest-Reforged/ConquestReforged#379]
**Mod Version & Build Number**    
Minecraft 1.16.5
ConquestReforged-mc1.16.5-5.0.6.jar (mod)
CRRP-1.16.5-5.0.6.zip (resource pack)
Downloaded from Curseforge/Overwolf

**Forge Version**    
v36.2.23

**Describe the bug**    
All modded carpet/cover blocks (Black Persian Rug Cover, Red Pazyryk Rug Cover etc) all seem to reference the vanilla Black Carpet texture instead of their modded texture.

**Screenshots/Video**    

![2022-02-04_10 39 51](https://user-images.githubusercontent.com/99043154/152587802-99331973-ac05-40fe-908e-fc09a2186f96.png)

![2022-02-04_11 04 32](https://user-images.githubusercontent.com/99043154/152587974-a5f52ad1-d028-4061-9bcb-825e27b82463.png)

**Comment by HIPPOKLEIDES** [comment]
Should be fixed for next release. Thanks
