### ISSUE TITLE
Possible massive unbalance in crafting "layers"

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#38]
So the recipe for a "layer" (for grass, dirt, etc) is 9 solid blocks. It yields sadly only 9 layers... And we know a layer is 1/8 of a block so you're basically using 9 blocks to reform 1 block and 1 layer. Huge loss.

I tried to build a simple ~15 blocks x 2-3 blocks easy-sloped path and it cost me so much dirt and gravel that i gave up and used the good ol' slab instead... Can't imagine smoothing a whole village's streets in Survival due to layers being so costy in resources.

I recommend that using 9 blocks yields 9 times a set of 8 layers items (so 72 layers total). It's a huge lot i know but the fact is with layers we often want to use up loads of layers for a single "block" space.

**Comment by HIPPOKLEIDES** [comment]
This is a really good point. I fixed the layer recipes to give 8 layers for every block used in the layer recipe.
