### ISSUE TITLE
1.16.5 Beta - Weathered Anorthosite blocks/variants have wrong texture

### ISSUE THREAD

**Issue by Jigglebrugal** [Conquest-Reforged/ConquestReforged#380]
**Mod Version & Build Number**    
Minecraft 1.16.5
ConquestReforged-mc1.16.5-5.0.6.jar (mod)
CRRP-1.16.5-5.0.6.zip (resource pack)
Downloaded from Curseforge/Overwolf

**Forge Version**    
v36.2.23

**Describe the bug**    
Weathered Anorthosite blocks (all variants) have the texture of Weathered Andesite instead of their own texture.

**Screenshots/Video**

![2022-02-04_10 44 42](https://user-images.githubusercontent.com/99043154/152589613-4c24a0c9-8258-45cd-98c8-dad1ccee6f27.png)

![2022-02-04_11 16 15](https://user-images.githubusercontent.com/99043154/152589637-5621b2e2-f606-4a19-8740-83e2710be0ea.png)

**Comment by HIPPOKLEIDES** [comment]
Got this one fixed for next release. Thanks
