### ISSUE TITLE
Problems with texture version 1.16.5

### ISSUE THREAD

**Issue by St4rkiller** [Conquest-Reforged/ConquestReforged#381]
Mod ConquestReforged-mc1.16.5-5.0.6
Resource Pack CRRP-1.16.5-5.0.6

Mod TreesOfConquest-1.0.0
DynamicTrees-1.16.5-0.10.0-Beta31 - (Mod I use together with Trees of Conquest)    

Forge Version 36.2.26

Hello, as soon as I start a new world, I come across connections of white and gray textures, in some places the water texture is invisible.
The second issue related to Mod TressOfConquest, the trees are with the default minecraft textures, others are with the Mod textures
I performed a test only with these mods in question, these problems persisted.

**Crash Log**    
I have no problems with crashes

**Screenshots/Video**    
![Image01](https://user-images.githubusercontent.com/99108040/152679488-b80dd5ce-b4cd-4127-b7d3-700dbc891b82.jpg)
![Image02](https://user-images.githubusercontent.com/99108040/152679492-36821b6a-6635-4d26-9878-051d6156a621.jpg)
![Image03](https://user-images.githubusercontent.com/99108040/152679496-f5fc3b3d-0ca8-486a-8283-32abbdec0448.jpg)

**System Information (optional)**    
Total RAM: 16 Gb   
Allocated RAM: 16 Gb    
CPU: Intel Core i5-10400
GPU: Geforce GTX 1060 6Gb

The images attached above I am using the Shader SEUS renewed version 11.0
I tested it without shader and with other shaders, but the textures don't appear as they should
I'm using the latest version of optifine available for version 1.16.5
OptiFine HD U G8

Note: I love this mod, congratulations on the work.

**Comment by HIPPOKLEIDES** [comment]
All the vanilla leaves seem to have the proper models with just CR

Can you show which block is missing the proper model by using the debug screen? This'll show us the ID of the block in question along whith its blockstates

**Comment by HIPPOKLEIDES** [comment]
As for the white and gray textures, I suspect that is caused by anistropic filtering or antialiasing, which are broken Optifine features.

**Comment by HIPPOKLEIDES** [comment]
With regard to the trees, DynamicTrees adds in its own leaves. Someone would need to make a compatibility pack for these leaves to use the new conquest models.
