### ISSUE TITLE
Sitting in chairs finicky on a server

### ISSUE THREAD

**Issue by HIPPOKLEIDES** [Conquest-Reforged/ConquestReforged#384]
Originally reported by AC
Sometimes unable to sit, sometimes able to sit. Strangely, a right click and then a left-shift seems to complete the process of dismounting the chair, despite not sitting in it. Sometimes this allows the chair to then be sit in, though not reliably.

**Comment by RafaelZ49** [comment]
how u fix that? cause that is making my lan crash
