### ISSUE TITLE
1.16.5 Simple Oak Fence and Old Simple Oak Fence Wrong texture and more

### ISSUE THREAD

**Issue by Moredir** [Conquest-Reforged/ConquestReforged#385]
Version: 1.16.5

When placing down, simple oak fence and old simple oak fence have the wrong texture. the item in hand has the correct texture
![2022-02-09_21 15 00](https://user-images.githubusercontent.com/85825065/153356737-ff1ac269-f906-4d72-a7b5-8a182fa221b0.png)

Simple Picket Fence has no breaking particle textures
![2022-02-10_08 20 18](https://user-images.githubusercontent.com/85825065/153357405-51579dd6-2abe-4a49-93d0-57981e425481.png)

**Comment by HIPPOKLEIDES** [comment]
Both should be fixed for next release. Thanks
