### ISSUE TITLE
All "newer" carpets are defaulting texture to the black carpet

### ISSUE THREAD

**Issue by xElandriax** [Conquest-Reforged/ConquestReforged#386]
**Mod Version & Build Number**    
ConquestReforged-mc1.16.5-5.0.6

**Forge Version**    
36.2.26

**Describe the bug**    
All of the newer carpets have bugged textures which are defaulting to the black (red-edged) carpet/wool block. Carpets show correct textures in GUI

**Crash Log**    
N/A

**Screenshots/Video**    
![2022-02-10_10 08 13](https://user-images.githubusercontent.com/66781812/153385852-a6323732-11e2-41ee-b59e-3a89eeccedb3.png)

**System Information (optional)**    
N/A

**Additional context**

**Comment by HIPPOKLEIDES** [comment]
Should be fixed for next release. Thanks
