### ISSUE TITLE
Weathered Anorthosite wrong texture in 1.16.5 beta

### ISSUE THREAD

**Issue by Agonizes** [Conquest-Reforged/ConquestReforged#387]
**Mod Version & Build Number**    
"ConquestReforged-mc1.16.5-5.0.6"

**Forge Version**    
Forge 35.2.26

**Describe the bug**    
The textures displayed on the Weathered Anorthosite block appear to be wrong, it seems to display the Weathered Andesite textures instead.
The Item model does display the correct textures afaik.

**Screenshots/Video**    
Hovering over the Weathered Anorthosite block:
![2022-02-11_19 46 22](https://user-images.githubusercontent.com/61914432/153651574-da5fb355-7625-4b2f-8b1d-4b2f81a7fde1.png)

Weathered Andesite:
![2022-02-11_19 46 26](https://user-images.githubusercontent.com/61914432/153651726-618df6d2-3022-4b44-884b-9fc3a5ca88da.png)

Hope this helps

**Comment by HIPPOKLEIDES** [comment]
Fixed for next update. Thanks
