### ISSUE TITLE
[1.16.5] Wall textures introduced by other mods break

### ISSUE THREAD

**Issue by Wiseclone** [Conquest-Reforged/ConquestReforged#388]
The top and bottom textures of walls from other mods break when Conquest Reforged is loaded.
An example log entry of the bug:

_[22:59:37] [Worker-Main-54/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #bottom in consistency_plus:block/smooth_stone_wall_post
[22:59:37] [Worker-Main-54/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #top in consistency_plus:block/smooth_stone_wall_post_

From the above, I assume Conquest is interfering with the _#top_ and _#bottom_ variables on walls whenever another mod calls them.

**Comment by HIPPOKLEIDES** [comment]
Should be fixed for the next update. Thanks
