### ISSUE TITLE
Smelting in an iron furnace turns it into a stone furnace and ejects items

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#39]
So i crafted an iron furnace. When the block updated to an "in use" furnace, the model switched to the regular stone furnace (with fire) and the iron ore i was gonna smelt got ejected from the furnace (like i breaked it). The piece of coal used to start the furnace is obviously consumed. Remaining "fuel" is ejected as well, if there's any.

Running Feb 18th Patreon's dev version

Before
![2018-04-06_21 27 17](https://user-images.githubusercontent.com/18398566/38449758-a5a01ac2-39e1-11e8-8363-9c2134551a6f.png)

After
![2018-04-06_21 27 21](https://user-images.githubusercontent.com/18398566/38449760-a8860fbc-39e1-11e8-9a50-3e87eb82200a.png)

**Comment by HIPPOKLEIDES** [comment]
This is indeed an issue, I'll probably squash this one in 1.13 as furnaces will be changing quite a bit in that update

**Comment by CreativeRealms** [comment]
Iron Furnace doesn't exist anymore as it has been replaced with the vanilla Blast Furnace.
