### ISSUE TITLE
[Potential Bug] (1.16.5) Marble plinth stairs rendering incorrectly when placed upside-down

### ISSUE THREAD

**Issue by RyanJM93** [Conquest-Reforged/ConquestReforged#391]
ConquestReforged-mc1.16.5-5.0.7.jar

forge-1.16.5-36.2.30

Marble plinth stairs (conquest:marble_plinth_stairs) do not render correctly when placed upside-down.

![unknown](https://user-images.githubusercontent.com/5819773/159563595-f65ccfa0-787c-4245-871a-38ad9c640950.png)

![bug_screenshot1](https://user-images.githubusercontent.com/5819773/159563629-d02f1d18-d6f2-472f-a098-15fd270395b0.PNG)

![bug_screenshot2](https://user-images.githubusercontent.com/5819773/159563673-92f39f78-5f89-4a53-b995-9b15c2e2355b.PNG)

**System Information (optional)**    
Total RAM:    32 GB
Allocated RAM:    12 GB
CPU:    i7-7700k (overclocked to 4.5Ghz)
GPU:    Gigabyte Aorus 2080 Super

This world was converted from 1.12.2 to 1.15, and then opened in 1.16.5. This is the only block state issue I've noticed so far with Conquest Reforged since conversion.

**Comment by HIPPOKLEIDES** [comment]
Thanks for the report. Should have it fixed for all plinth stairs in next update
