### ISSUE TITLE
[Potential Bug] (1.16.5) 2 meter arches no longer have corner variants

### ISSUE THREAD

**Issue by RyanJM93** [Conquest-Reforged/ConquestReforged#392]
ConquestReforged-mc1.16.5-5.0.7.jar

forge-1.16.5-36.2.30

2 meter arches (in this case, conquest:sandstone_brick_two_meter_arch) no longer have corner variants, when they did in previous versions of the mod.

![2022-03-29_22 46 42](https://user-images.githubusercontent.com/5819773/160857989-6e9494b0-d1bb-4a04-bc52-38a578454a3d.png)

1.12.2 version of same building for reference

![2022-03-29_22 59 41](https://user-images.githubusercontent.com/5819773/160858085-2e0874e0-9516-4ff4-bb87-1d79a0479a32.png)

System Information (optional)
Total RAM: 32 GB
Allocated RAM: 12 GB
CPU: i7-7700k (overclocked to 4.5Ghz)
GPU: Gigabyte Aorus 2080 Super

This world was converted from 1.12.2 to 1.15, and then opened in 1.16.5.

**Comment by HIPPOKLEIDES** [comment]
the corners were removed
