### ISSUE TITLE
Wall Mounted Antlers (both Moose and Deer) flicker when placed on block

### ISSUE THREAD

**Issue by TomWTG** [Conquest-Reforged/ConquestReforged#394]
**Mod Version & Build Number**    
ConquestReforged-mc1.18.2-7.0.3

**Forge Version**    
1.18.2-forge-40.1.0

**Describe the bug**    
Wall Mounted Deer Antlers & Wall Mounted Moose Antler blocks flicker with the block on which they are placed.

**Screenshots**   

![2022-06-30_22 01 11](https://user-images.githubusercontent.com/108491961/176767952-bfb4941d-1059-4b64-830f-24eb8385e18d.png)

(F3 Screenshots, they don't really show the flickering issue) 
![2022-06-30_22 03 48](https://user-images.githubusercontent.com/108491961/176767947-1db47af7-af98-4ebb-b17a-d3345ae64b31.png)
![2022-06-30_22 03 47](https://user-images.githubusercontent.com/108491961/176767953-69c3ac07-edfd-448b-b4f9-e28bcba43d1b.png)

**System Information (optional)**    
Total RAM:   32GB
Allocated RAM:   16GB
CPU:   i7-8700 @3.20GHz
GPU: NVidia RTX 3060 Ti 

**Additional context**    
Only the frame of the texture flickers, the skull itself is fine.

**Comment by HIPPOKLEIDES** [comment]
Fixed in latest fabric version
