### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoSuchFieldError: ATTACK_RANGE Exit Code: -1

### ISSUE THREAD

**Issue by lilithsspawn** [Conquest-Reforged/ConquestReforged#397]
**Mod Version & Build Number**
Forge 1.18.2_40.1.0
ConquestReforged-mc1.18.2-7.0.3
OptiFine_1.18.2_HD_U_H7
TerraForged-1.18.2-0.3.1-alpha-2.jar

**Forge Version**    
1.18.2_40.1.0

**Crash Log**    
https://pastebin.com/WiqHCCF6

**System Information**    
Total RAM:  32GB@3333MHz
Allocated RAM:  max. 16GB
CPU: AMD Ryzen 3700X@4.3GHz
GPU: AMD Radeon 5700XT

**Comment by HIPPOKLEIDES** [comment]
This error comes from the Medieval Arms and weapons mod when the latest version of Forge isn't used.
