### ISSUE TITLE
Suggestion - Flowers and dyes

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#40]
Assign a crafting recipe to create dyes for all Conquest Reforged flowers out there!

Scenery is so colourful but, sadly, only default plants can be turned into dyes.

**Comment by HIPPOKLEIDES** [comment]
This is a pretty good suggestion, I'll see if I can get to it soon

**Comment by HIPPOKLEIDES** [comment]
implemented

**Comment by boivsamuel** [comment]
You sure are active mate!
