### ISSUE TITLE
Renameable

### ISSUE THREAD

**Issue by IVIR-Alaska** [Conquest-Reforged/ConquestReforged#403]
**Mod Version & Build Number**    
The specific mod & its version in question.    
You can copy-paste the mod jar's filename here.
appleskin 1.19
jei 1.19.3
journeymap 1.19.3
optifine 1.19.3
**Forge Version**    
The specific version of Forge you are currently using.
44.1.0
**Describe the bug**    

For shields and weapons when trying to rename an item for the alternate skins, they turn into pink and black blocks. It works for ingots, nuggets, armor, and food that I have tried, but not for weapons or shields.
**Crash Log**    
If your game crashed please upload a crash log (pastebin.com being the preferred method).

**Screenshots/Video**    
Provide screenshots or video to aid your bug description.  
If the issue relates to a block, please screenshot it with the `F3` debug menu open and your crosshair over the block you're reporting (this allows us to see exactly what blockstate is affected).

**System Information (optional)**    
Total RAM:    
Allocated RAM:    
CPU:    
GPU:

**Additional context**    
![Screenshot_20230223_035033](https://user-images.githubusercontent.com/126206767/221044682-9da31e5d-e0a2-455f-bb01-6d3d561fb0cd.png)

**Comment by HIPPOKLEIDES** [comment]
I believe this is an Optifine issue. Regardless, Conquest Reforged is not on 1.19.3. 

For support with the vanilla Conquest pack, you should go here: https://discord.gg/ehTcUDk
