### ISSUE TITLE
Issues with 3D modeling

### ISSUE THREAD

**Issue by JBuckets33** [Conquest-Reforged/ConquestReforged#405]
**Fabric 1.19.2**    

When loading specific mobs on fabric 1.19.2 (loaded on ATLaucher), there are problems with the 3D modeling of specific mobs. More specifically, the following mobs do not have 3D modeling in their faces: cat, ocelot, cow, mooshroom, rabbit, sheep, pig, and axolotl.

**Comment by HIPPOKLEIDES** [comment]
Fixed in latest version
