### ISSUE TITLE
Duplicated Gilded Bronze Block (with different IDs and recipes)

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#41]
There's 2 gilded bronze blocks. One that can be crafted into loads of things and one that doesnt.

Perhaps the non-crafting block should be removed?

![2018-04-07_18 44 42](https://user-images.githubusercontent.com/18398566/38461014-fa7dd964-3a93-11e8-98f4-d1725eaf5896.png)
![2018-04-07_18 44 44](https://user-images.githubusercontent.com/18398566/38461015-fcd082f2-3a93-11e8-9ca3-0ca9fdf61f9e.png)

**Comment by HIPPOKLEIDES** [comment]
One is meant to have a different side texture than the other (and it does now :) ). Thanks for the report.
