### ISSUE TITLE
Horse Chestnut + Downy WIllow Saplings texture missing

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#42]
Black and Magenta checkered frame displayed instead of a real texture.

![2018-04-07_21 47 15](https://user-images.githubusercontent.com/18398566/38462040-5d12f24e-3aad-11e8-8c69-5716f317997c.png)

![2018-04-08_10 50 46](https://user-images.githubusercontent.com/18398566/38468916-b9edded0-3b1a-11e8-84c3-01dc44eb020e.png)

**Comment by HIPPOKLEIDES** [comment]
all sapling textures are in now :)
