### ISSUE TITLE
There's a Layered Chalk recipe that takes Weathered Andesite vertical slabs

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#46]
I think this recipe is mixed up...

![2018-04-09_12 30 37](https://user-images.githubusercontent.com/18398566/38510094-ec3bd0fe-3bf1-11e8-9847-b8f01a067ef5.png)

**Comment by HIPPOKLEIDES** [comment]
Got that fixed. Thanks
