### ISSUE TITLE
Stucco recipe no longer works once the paint brush begins to be used

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#47]
Worked the first time but no longer does once the paint brush has began being used.

![2018-04-09_12 36 45](https://user-images.githubusercontent.com/18398566/38510436-15c20c8a-3bf3-11e8-8b1f-12d5d39c763a.png)

The paint brush's resource also looks not good somehow with the ".name" in the label.

**Comment by HIPPOKLEIDES** [comment]
Good catch, thanks. It's fixed now (names too)

**Comment by boivsamuel** [comment]
@HIPPOKLEIDES I seems to have encountered the same issue with the light red wall recipe... Was it fixed for all colors?

**Comment by boivsamuel** [comment]
Green wall as well...
