### ISSUE TITLE
Painting chooser feature removes stacked paintings from inventory

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#48]
Crafted 8 painting, all stacked on the same slot then hit "C" to choose the painting i wanted with the new painting-chooser feature. 

My stack of 8 paintings was replaced by a single painting of the name i chose. The 7 others are gone.

Perhaps see if it is possible to replace only one of the stacked item in the paintings stack with the chosen painting and keeping the others?

**Comment by dags-** [comment]
Fixed, thanks!

(The expected behaviour would be that the artwork is set for the entire stack - inventory management is down to the user, they can split the stack themselves if they want one stack to be one type of painting, and another stack to be another)

**Comment by boivsamuel** [comment]
Anytime!
