### ISSUE TITLE
Fishscale cobble recipe broken

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#49]
The combination of Old Cobblestone and Cobblestone suggested by the recipe book won't craft into the desired Fishscale Cobble block.

![2018-04-09_21 57 32](https://user-images.githubusercontent.com/18398566/38532162-802bb7e4-3c41-11e8-8e4e-1300db8527ea.png)

**Comment by HIPPOKLEIDES** [comment]
Thanks! I fixed it
