### ISSUE TITLE
Suggestion - Travertine Limestone in WorldGen

### ISSUE THREAD

**Issue by TheProtoss-YT** [Conquest-Reforged/ConquestReforged#5]
Unless I am missing something, Travertine is a mineral rich limestone and should be found in geothermal hot springs or deserts around water or old water ways. The current plan to use Diorite and Granite feels sort of forced (late night at the office perhaps?) It feels like something that should be found adding beauty and diversity in the world gen not something to craft with mountain ashlars.  Thanks for hearing me out have a good day!

https://en.wikipedia.org/wiki/Travertine

**Comment by CreativeRealms** [comment]
Closed because world gen will be completely reworked in 1.17.
