### ISSUE TITLE
Crafting a (tool) hammer can yield up to as many (decoration) hammer as there are durability units

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#50]
Accidentally crafted 64 decoration hammers by double shift-clicking by mistake the Old Cobblestone recipe.

The first shift-click transformed my hammer and a stack of 64 Cobblestone into 64 Old Cobblestone. The hammer remained in the crafting table and my twitchy finger performed a second shift-click which turned the "tool" hammer into 64 "decoration" hammers and used up 64 units of durability in my source "tool" hammer.

Perhaps, it would make more sense to make a single decoration hammer out of one tool hammer?

**Comment by HIPPOKLEIDES** [comment]
I've made it so that only an undamaged hammer can be turned into the decoration hammer to avoid these sorts of situations. Thanks!
