### ISSUE TITLE
Glass connected textures

### ISSUE THREAD

**Issue by domusan** [Conquest-Reforged/ConquestReforged#53]
Since I updated to the lasted dev version, all glass connected textures do not work. They work for other blocks though. Anybody else having that issue?

**Comment by domusan** [comment]
Edit: most of them actually work. The ones that do not work are: carved Gothic, fancy class, dragon glass.

**Comment by HIPPOKLEIDES** [comment]
They're working fine for me, so there's probably something wrong with your world (an old one, used other mods, shifted ids)
