### ISSUE TITLE
Spawning in Trees

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#54]
The last couple of times that I've spawned a new world, I've spawned up in a tree. This isn't always a problem because you can climb down through the leaves, but it's a little unnerving. I'm using the most recent dev version for 1.12.2.

**Comment by HIPPOKLEIDES** [comment]
Haven't experienced this myself and regardless I'm not sure this really is an issue... so I'm closing this one for now.
