### ISSUE TITLE
Mismatched Tree Behavior

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#56]
- Acacia Sapling (#7063/5 from conquest:leaves_fullbiome_3@0) and Dark Oak Sapling (#7062/5 from conquest:leaves_fullbiome_3@1) grow into a small tree with beech logs and horse chestnut leaves, and they drop horse chestnut saplings (No Texture). If I craft the beech logs in a craft table, it gives me ash planks... 

- Oak Sapling (#7063/0 from conquest:leaves_fullbiome_2@0 and conquest:leaves_fullbiome_2@12) from breaking leaves grows a grape vine shrub thing that drops grape vine saplings.

- Rowan Tree Sapling (#7062/3) grows into a tree with spruce logs and gorse leaves and drops Gorse Sapling (#7049/3) (No Texture).

- Breaking leaves with a tool like an ax causes the leaves to not drop anything.

**Comment by SirChamomile** [comment]
Not exactly related so I won't put it in the issue, but many of the wood-like blocks, logs and planks aren't in the dictionary so mods don't see them as usable. I'm pretty sure this is on the roadmap though, as it isn't very difficult to add.

**Comment by HIPPOKLEIDES** [comment]
Should be fixed now, thanks.

As for OreDictionary, it is something I'd really like to look into in 1.13. I don't see it happening in 1.12 as the flattening would render so much work useless upon updating.

**Comment by SirChamomile** [comment]
Thanks for the hard work on this. Are you updating the download link on Patreon with every round of bug fixes or are they being released in conjunction with every Patreon post update? I'm assuming it's the later. I didn't see versioning on the files but maybe I'm not looking close enough.
