### ISSUE TITLE
Missing stair block

### ISSUE THREAD

**Issue by Spejs** [Conquest-Reforged/ConquestReforged#59]
Big black slab doesn't have a stair variant, at least in 1.10. I checked other big slabs, and they all have it.

**Comment by Spejs** [comment]
I thought it was a bug, since it has both slabs, corner block and other variants, and it shouldn't be hard to add that stair to 1.12. What a pity it has to wait for 1.13.

**Comment by CreativeRealms** [comment]
Fixed in the next update. 1.10/1.12 aren't getting additional updates.
