### ISSUE TITLE
Conquest Hammer spawns random items in Crafting Table

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#60]
When I have the conquest hammer in my inventory I get all sorts of random items spawning in the output slot of the crafting table as soon as I open the table's UI. These have been shears and iron ingots so far, but I haven't tested it extensively. I can pull them out of thin air though. I know these items are in development though and I'm sure you're aware they act peculiarly.

**Comment by HIPPOKLEIDES** [comment]
No, nothing such as this has ever happened with the hammer in my inventory

**Comment by SirChamomile** [comment]
I'm going to test again this evening. I'll see if I can do a screen cap of this behavior. It could be an interaction with inventory sorter or inventory tweaks. I'm interested in testing mod interactions, so I'm running a couple dozen mods alongside conquest.

**Comment by HIPPOKLEIDES** [comment]
I suspect that you installed/removed some mods and entered an old world, therefore shifting its numerical ids for blocks at the very least. 

This is an unfortunate consequence of how worlds remember things and how many mods (eg: Optifine, worldedit) themselves look at them, perhaps it will improve in 1.13

**Comment by SirChamomile** [comment]
Actually all of my testing is being done in the same world in Survival with the same modlist. However, I have popped in and out of JEI's creative functions, and that's what might have done it.

**Comment by wunder-bread** [comment]
@SirChamomile ,
When Bug Testing, you want to do it in a "Pure" as can be environment. We can't chase bugs for everyone else's Mods out there. (especially when you are running "a couple dozen mods alongside conquest". That's asking for false positives all day.

**Comment by SirChamomile** [comment]
Thanks Wunder-bread. I'm just playing the game and reporting some bugs along the way. I'll refrain from reporting bugs that could potentially be from mod interactions from now on. If it's something persistent I'll create a test environment and put it here.

**Comment by HIPPOKLEIDES** [comment]
Feel free to report possible mod incompatibilities. In any case, as this issue is highly unlikely to be from our mod I will close this issue
