### ISSUE TITLE
Saplings and Plants grow on Stone

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#61]
Like the description says, saplings and plants can be planted on stone blocks of any type, as well as gravel. Other mods spawn on these surfaces as well.

**Comment by HIPPOKLEIDES** [comment]
I'd rather not restrict regular builders from placing plants on whatever they want for the sake of a survival mechanic (seeds are an exception to this).

**Comment by SirChamomile** [comment]
The only problem with that is when mods like botania spawn plants on things like stones. It's not a huge deal, but maybe if you could just specify minecraft and conquest for spawning on stone? That's the only reason I suggested it.
