### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#62]
- No recipe for Old Wood Beam (#7047/0)
- Also Old Wood Beam (#7047/0) and Horizontal Old Wood Beam (#7048) share the same recipe.
- No recipe for Birch Beam Fence (#6439/1)
- No recipe for Wooden Pole (#7126)

**Comment by HIPPOKLEIDES** [comment]
fixed these
