### ISSUE TITLE
Tree leaves grow over Old Cobblestone

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#65]
A tree sappling grew next to an Old Cobblestone wall and the leaves replaced a few of the stone blocks when the tree matured.

Hot screenshots on PC but on my phone right now.

**Comment by DirtyNative** [comment]
This needs to be fixed as soon as possible

**Comment by CreativeRealms** [comment]
Won't be fixed in 1.12.2 but likely will be in 1.15.2.
