### ISSUE TITLE
Cobblestone trapdoor has same recipe as vanilla cobblestone wall.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/ConquestReforged#68]
![2018-04-17_11 14 36](https://user-images.githubusercontent.com/33978024/38857108-11b60738-4231-11e8-9a50-4633d7eea9d6.png)
![2018-04-17_11 14 47](https://user-images.githubusercontent.com/33978024/38857112-149f6ebc-4231-11e8-9eae-2cd0c4f85e9a.png)

**Comment by HIPPOKLEIDES** [comment]
fixed, thanks
