### ISSUE TITLE
Purple concrete is Poor Roman Bricks

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#69]
Dunno if that is desired, but the Purple Concrete has the texture of Poor Roman Bricks....

![2018-04-14_22 15 20](https://user-images.githubusercontent.com/18398566/38939674-76a27f44-42f6-11e8-8ad7-e1b1fad6ba6a.png)
![2018-04-14_22 15 30](https://user-images.githubusercontent.com/18398566/38939683-7b71cce6-42f6-11e8-8083-fec9f435fdf6.png)

**Comment by HIPPOKLEIDES** [comment]
it's seperated into a new mod block after 1.12
