### ISSUE TITLE
Conquest Reforged World type - Durability of natural objects too high

### ISSUE THREAD

**Issue by Ashurthebear** [Conquest-Reforged/ConquestReforged#7]
- More work to remove brush covering tundra than to chop down a tree
- digging below shale requires an iron pickaxe (I could find no iron or coal deposits at all, but found one in a village blacksmith) and even then it was almost like digging through obsidian.

The whole world type seems WAY too arduous, even for an avid survival player. I could only make stone objects from cobblestone in villages and dungeons. The recipes for common tools did not work with grayweak (sp?) and shale.

**Comment by HIPPOKLEIDES** [comment]
durability and resistance for those blocks should be fixed now
