### ISSUE TITLE
Recipes lack a bit flexibility (2x2 vs 3x3)

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#70]
So some recipes that would require only a 2x2 space to place items are craftable only in a crafting table. It's not something we're use to seeing in Vanilla recipes normally...

And example is the Chisel tool, with only a 2 item recipe:
![2018-04-14_21 37 33](https://user-images.githubusercontent.com/18398566/38939862-d3a143c4-42f6-11e8-9a6c-c1e91e6c584e.png)

However, in just the 2x2 Inventory space, the same combination doesnt yield a chisel:
![2018-04-14_21 37 40](https://user-images.githubusercontent.com/18398566/38939864-d3ef1c70-42f6-11e8-9c61-eadb18e390fb.png)

**Comment by HIPPOKLEIDES** [comment]
Went through all the recipe files and got rid of extra white spaces that were causing this, so in the next build they should be flexible like vanilla recipes
