### ISSUE TITLE
Roman Brick with Peach Stucco has no recipe

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#71]
So i have discovered all ingredients to make Roman Bricks and Peach Stucco, but there is no recipe in the book to make the block that combines both textures. The only way to craft such a block is to take 2 vertical or horizontal slabs and put them together...

![2018-04-14_22 27 53](https://user-images.githubusercontent.com/18398566/38940028-3b882b92-42f7-11e8-8694-95aec4b59c29.png)

**Comment by HIPPOKLEIDES** [comment]
That block isn't completely finished, so I've removed it's recipes from being unlocked by the advancement for now
