### ISSUE TITLE
Small Arch using wrong textures

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#72]
Roman Mosaic Small Arche is linked to the Grey Tiles texture : ![2018-04-14_22 28 28](https://user-images.githubusercontent.com/18398566/38940124-72345918-42f7-11e8-9b82-0062cd4238bd.png)

Also, check for more of these small arches textures as the Old Cobble Stone Small Arch also seem to have an issue. It seems like an icy/snowy version of the Old Cobblestone
![2018-04-12_16 03 41](https://user-images.githubusercontent.com/18398566/38940667-c0a6d714-42f8-11e8-8c95-ed44211259cc.png)

I didnt check them all yet.

**Comment by HIPPOKLEIDES** [comment]
Looks like a few names for the Small Arches were offset to the next Small Arch. Should be fixed now
