### ISSUE TITLE
Possible tie to #70 : 2x2 Pine planks wont make a crafting table

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#74]
Got lost in the Mountains biome and all i had was Pine tress that i turned into planks but it woulnt make a Crafting table from this custom wood. Perhaps the recipe is missing or that's related to #70 where you cant make some custom CR recipes outside of the 3x3 crafting table.

![2018-04-14_22 45 03](https://user-images.githubusercontent.com/18398566/38940990-8c8fb648-42f9-11e8-9c4b-49a8003189c8.png)

**Comment by HIPPOKLEIDES** [comment]
As with the bed issue, this should be fixed by adding the planks to OreDictionary
