### ISSUE TITLE
Pine planks wont yield a bed

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#75]
So after cheating (#74) to make a crafting table (Creative Mode), i got back into Survival Mode and tried to make a bed out of Pine planks. Nope!

![2018-04-14_22 45 56](https://user-images.githubusercontent.com/18398566/38941080-bf54af48-42f9-11e8-89a4-71db769d7b7f.png)

**Comment by HIPPOKLEIDES** [comment]
Added the planks to the OreDictionary so this shouldn't an issue for any of our planks now, thanks :)
