### ISSUE TITLE
Naturally generated Village was filled by the Zombie version of the Villager mob...

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#76]
I wanted to find a Village so i typed `/locate Village`, went to the coords (in daytime) and i was greeted by a dozen infected Zombie Villagers. I doubt some zombies began infecting regular villagers hundreds of chunks away...

Perhaps it's desired to have infected or cursed villages generated but i never heard of that.

![2018-04-14_23 08 20](https://user-images.githubusercontent.com/18398566/38941194-07f5d772-42fa-11e8-853a-fa500345c3a5.png)

**Comment by HIPPOKLEIDES** [comment]
"A village has a 2% chance of generating as a zombie village," (https://minecraft.gamepedia.com/Village#Generation)

Unless this is happening with all villages, I think this is working as intended
