### ISSUE TITLE
The "a" on signs is not rendered normally

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#77]
This one has bugged me for a while...

The `a` on the signs in CR (using HD fonts) always look wierd:

![2018-04-15_08 24 34](https://user-images.githubusercontent.com/18398566/38941509-b1b7aa1a-42fa-11e8-9bc7-7f9d8642a40e.png)

**Comment by HIPPOKLEIDES** [comment]
Signs have a history of being glitchy with Optifine and shader-packs. I tried to recreate this myself, but had no luck in doing so (even while using Custom Fonts, which I assume you refer to as HD fonts). I'd recommend making sure your shader-packs, Optifine, and graphics drivers are up to date
