### ISSUE TITLE
Suggestion - Natural luminescent blocks

### ISSUE THREAD

**Issue by Kranchan** [Conquest-Reforged/ConquestReforged#8]
Luminescent blocks/creatures would be a good addition. Here are some examples.

Jellyfish
https://www.hakaimagazine.com/wp-content/uploads/facebook-bioluminescence_0.jpg

Plankton
https://aqua.org/-/media/Images/Oceans-A-to-Z/Landing-Page-Images/B---Bioluminescence.ashx?la=en&hash=D4B3624D6F2C015DF2D70A18B598B7DC43F395EA

Mushrooms
https://media.mnn.com/assets/images/2015/04/Mycena-chlorophos_0.jpg.838x0_q80.jpg

Stones
https://www.coregravel.ca/site/assets/files/1027/core-glow-driveway.jpg

**Comment by CreativeRealms** [comment]
Will be a thing in 1.17-1.18.
