### ISSUE TITLE
The "Bow Saw" recipe gives the Decoration block instead of the Tool at first

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#81]
If it followed the Hammer's or (weapon) Bow's logic, you'd first craft the Tool/Weapon version then have the choice to take the tool/weapon and convert it into a Decoration block to have the object lying around on a table top...

Perhaps fix the output of the sticks/ingots recipe and then change the Tool Bowsaw makes a Decoration Bow Saw?

![2018-04-21_14 39 03](https://user-images.githubusercontent.com/18398566/39087631-c9f318c0-4571-11e8-8eac-f3d5a6ecca40.png)

**Comment by boivsamuel** [comment]
Also... building Wattle Fence, my 2 Bow Saws (tool) seems to have turned into a single (used) Bow Saw... not sure how it happened...

**Comment by HIPPOKLEIDES** [comment]
As with the hammer, I have now removed the recipe for the decorational version to avoid these issues
