### ISSUE TITLE
Suggestion : Decaying pine-cones

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#82]
I'm not sure if it's possible but pine cones should decay just like Pine Needles so we don't end up with floating pine cones once the Pine Needles (leaves) have decayed when the trunk of a Pine tree is axed. A bit like vanilla Vines just break apart when the adjacent leaves block is decaying.

![2018-04-21_15 22 47](https://user-images.githubusercontent.com/18398566/39087969-de279946-4577-11e8-9fb6-861f39b8657e.png)

**Comment by HIPPOKLEIDES** [comment]
This is definitely a good idea. It is something I will certainly plan on setting up once we go through the flattening (1.13)

**Comment by CreativeRealms** [comment]
Duplicate issue
