### ISSUE TITLE
Offset in "Debris" Layer recipe

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#83]
Please check for an offset in "Debris" Layers recipes... Some Layers outputs match their Block types but others dont...

- Schist Debris gives Sandstone Debris Layer.
- Sandstone Debris gives Smooth Colored Pebbles Layer

![2018-04-21_16 19 10](https://user-images.githubusercontent.com/18398566/39088448-3ac4ff42-4580-11e8-9004-bd266c09cfbb.png)

![2018-04-21_16 19 20](https://user-images.githubusercontent.com/18398566/39088449-3ad501da-4580-11e8-8bfd-ba238c81fbd8.png)

**Comment by HIPPOKLEIDES** [comment]
Seems like they all just got mixed around. Anyways, they're fixed now. Thanks!
