### ISSUE TITLE
Duplicate Dark Dirt Path blocks

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#84]
So i went out to find that naturally generated Light/Medium/Dark Dirt Path blocks after you told me they existed out there... Alder Swap and Mountains had plenty however i found a version that cannot be be crafted into layers or slab (ID 5339/7).

The recipe book tell me i should be able to craft layer or slabs with a block ID 5340/8

![2018-04-21_19 39 19](https://user-images.githubusercontent.com/18398566/39089768-82926582-459c-11e8-9242-3b403baa88b8.png)
![2018-04-21_19 39 22](https://user-images.githubusercontent.com/18398566/39089769-829f170a-459c-11e8-85d5-46cd33f3e755.png)

**Comment by HIPPOKLEIDES** [comment]
added recipes for those dirt paths
