### ISSUE TITLE
Clean Light Grey Stucco is a circular recipe.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/ConquestReforged#86]
Clean light grey stucco requires clean light grey stucco in order to craft. This makes it unobtainable in-game. In addition, gold nuggets make it a bit too expensive as a basic block. Maybe grey stucco + chisel = clean light grey stucco instead?

![screenshot_1](https://user-images.githubusercontent.com/33978024/39097705-a525c770-4668-11e8-87bc-16283faab1c0.png)

**Comment by HIPPOKLEIDES** [comment]
good catch, that was a strange recipe...anyway the recipe resembles the other recipes for stuccos now
