### ISSUE TITLE
Possibility to DISABLE the World Generator from Conquest / the OreRemover/Generator? (more Options)

### ISSUE THREAD

**Issue by Paepodlun** [Conquest-Reforged/ConquestReforged#89]
More Settings for the new world generator from Conquest (what biome do spawn, wich not) and if vanilla Ore spawning should be not overwritten as option would be great.

**Comment by dave1505** [comment]
Is this the reason I can't find any vanilla ores whatsoever? Please give us an option to change this, by not messing with any of the ore generation

**Comment by aaronegger** [comment]
Jep the vanilla ore generation gets broken by this mod. I am searching for a solution for this..

**Comment by CreativeRealms** [comment]
Fixed in 1.14.
