### ISSUE TITLE
Pine plank block model doesn't match the texture.

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#90]

**Comment by con-reforged-dev** [comment]
please provide more information /screenshots

**Comment by SirChamomile** [comment]
My bad, I meant pine planks.

![2018-05-01_21 52 20](https://user-images.githubusercontent.com/23204608/39503627-92f1a33c-4d8c-11e8-938c-b91c374d960e.png)

**Comment by CreativeRealms** [comment]
Fixed in 1.15.2.
