### ISSUE TITLE
Recipe discovery missing

### ISSUE THREAD

**Issue by boivsamuel** [Conquest-Reforged/ConquestReforged#93]
I know Sticks, i know Wood Planks. But the recipe book wouldn't tell me the recipe for stairs railings or straight railings until i used the `/recipe give @p *` command to look them up.

The recipes should be made available once both Sticks and Planks are known.

**Comment by HIPPOKLEIDES** [comment]
I unlock them as soon as I create a new world and enter the game like the other conquest recipes, so might be something on your end? otherwise I fixed it sometime between now and the last dev build
