### ISSUE TITLE
Nailed oak planks are very expensive.

### ISSUE THREAD

**Issue by CreativeRealms** [Conquest-Reforged/ConquestReforged#95]
Maybe replace iron ingots with iron nuggets?
(note had to get out of bed for this because Dukon is mean)

**Comment by SirChamomile** [comment]
I thought this same thing. There are a few recipes like this that make me want to scratch my head. Especially with the scarcity of iron in this pack.

**Comment by HIPPOKLEIDES** [comment]
changed ingots to nuggets ;)
