### ISSUE TITLE
Rowan Leaves as glass?

### ISSUE THREAD

**Issue by SirChamomile** [Conquest-Reforged/ConquestReforged#96]
Is this just me?

![2018-04-27_18 03 24](https://user-images.githubusercontent.com/23204608/39388698-a91ced3a-4a47-11e8-9cc0-c4bc78758c79.png)

**Comment by HIPPOKLEIDES** [comment]
Just you. Be careful with shifting ids, Optifine doesn't play nice with them

**Comment by SirChamomile** [comment]
After removing and re-adding some mods, I was able to make this issue go away, but I'm curious as to what the root cause is.
