### ISSUE TITLE
Bug with circular menu

### ISSUE THREAD

**Issue by Spejs** [Conquest-Reforged/ConquestReforged#98]
In the tab of the circular menu, which helps to pick blocks by colour, if I press "refresh" button, it lets me to pick block, but can't place it in the hotbar. v1.12

**Comment by CreativeRealms** [comment]
I'll add to this that the translucent menu background disappears when the wheel is shown and then reappears then it isn't.

Translucent background:
![2018-04-28_21 48 11](https://user-images.githubusercontent.com/33978024/39399846-f9256726-4b2d-11e8-8e7a-6635fb69177c.png)

Clear background:
![screenshot_1](https://user-images.githubusercontent.com/33978024/39399855-1439734a-4b2e-11e8-8c68-f9cfc75eb180.png)
