### ISSUE TITLE
1.12.2 CR animal textures not working

### ISSUE THREAD

**Issue by notdavid123** [Conquest-Reforged/ConquestReforged#99]
The new textures for pigs and chickens are not showing up. Additionally, when scrolling through miscellaneous there are two sets of spawn eggs/scrolls. One can scroll through and see chicken, cow, villager egg etc., then when you keep scrolling there are duplicates. Love all of the changes with 1.12.2 btw.

**Comment by dags-** [comment]
Provide a screenshot for anything visual please.
Defo got the resourcepack enabled as well?

**Comment by CreativeRealms** [comment]
Animal models were not implemented into the mod but may be in the future.
